export const planData = {
  object: 'list',
  data: [
    {
      id: 'price_1IxRIuHnywB98SRrYEIsDSWs',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622529740,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        description: 'Tour Seat Plan',
        EqualPlan: 'Paid-TourPlan',
        type: 'tourseat',
      },
      nickname: 'Paid-TourPlan-Yearly',
      product: 'prod_G9k7tNPy0S4UNh',
      tiers: [
        {
          flat_amount: 0,
          flat_amount_decimal: 0,
          up_to: 20,
        },
        {
          flat_amount: 200000,
          flat_amount_decimal: 200000,
          up_to: 40,
        },
        {
          flat_amount: 290000,
          flat_amount_decimal: 290000,
          up_to: 60,
        },
        {
          flat_amount: 360000,
          flat_amount_decimal: 360000,
          up_to: 80,
        },
        {
          flat_amount: 440000,
          flat_amount_decimal: 440000,
          up_to: 100,
        },
        {
          flat_amount: 999900,
          flat_amount_decimal: 999900,
        },
      ],
      tiers_mode: 'volume',
      usage_type: 'licensed',
    },
    {
      id: 'price_1IxRGgHnywB98SRrrJAKMtNw',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622529602,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        description: 'Tour Seat Plan',
        EqualPlan: 'Paid-TourPlan-Yearly',
        type: 'tourseat',
      },
      nickname: 'Paid-TourPlan',
      product: 'prod_G9k7tNPy0S4UNh',
      tiers: [
        {
          flat_amount: 0,
          flat_amount_decimal: 0,
          unit_amount: 0,
          unit_amount_decimal: 0,
          up_to: 20,
        },
        {
          flat_amount: 20000,
          flat_amount_decimal: 20000,
          unit_amount: 0,
          unit_amount_decimal: 0,
          up_to: 40,
        },
        {
          flat_amount: 29000,
          flat_amount_decimal: 29000,
          unit_amount: 0,
          unit_amount_decimal: 0,
          up_to: 60,
        },
        {
          flat_amount: 37500,
          flat_amount_decimal: 37500,
          unit_amount: 0,
          unit_amount_decimal: 0,
          up_to: 80,
        },
        {
          flat_amount: 45000,
          flat_amount_decimal: 45000,
          unit_amount: 0,
          unit_amount_decimal: 0,
          up_to: 100,
        },
        {
          flat_amount: 99900,
          flat_amount_decimal: 99900,
          unit_amount: 0,
          unit_amount_decimal: 0,
        },
      ],
      tiers_mode: 'volume',
      usage_type: 'licensed',
    },
    {
      id: 'price_1Ivbe5HnywB98SRrEpNA5YKc',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622092837,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        description: 'Grand Tourer',
        firstPurchase: '20',
        level: 'top',
        EqualPlan: 'Grand Tourer',
        type: 'orgseat',
        bundleProduct: 'Paid-TourPlan-Yearly',
      },
      nickname: 'Grand Tourer-Yearly',
      product: 'prod_FBpUnzhhfVzyra',
      tiers: [
        {
          flat_amount: 630000,
          flat_amount_decimal: 630000,
          up_to: 20,
        },
        {
          unit_amount: 30000,
          unit_amount_decimal: 30000,
        },
      ],
      tiers_mode: 'graduated',
      usage_type: 'licensed',
    },
    {
      id: 'price_1IvbdMHnywB98SRr4YNkx7l4',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622092792,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        level: 'top',
        description: 'Grand Tourer',
        EqualPlan: 'Grand Tourer-Yearly',
        firstPurchase: '20',
        type: 'orgseat',
        bundleProduct: 'Paid-TourPlan',
      },
      nickname: 'Grand Tourer',
      product: 'prod_FBpUnzhhfVzyra',
      tiers: [
        {
          flat_amount: 60000,
          flat_amount_decimal: 60000,
          up_to: 20,
        },
        {
          unit_amount: 2500,
          unit_amount_decimal: 2500,
        },
      ],
      tiers_mode: 'graduated',
      usage_type: 'licensed',
    },
    {
      id: 'price_1IvbZlHnywB98SRrnazyfJ73',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622092569,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        description: 'Tourer',
        firstPurchase: '8',
        EqualPlan: 'Tourer',
        bundleProduct: 'Paid-TourPlan-Yearly',
        type: 'orgseat',
      },
      nickname: 'Tourer-Yearly',
      product: 'prod_FBpUnzhhfVzyra',
      tiers: [
        {
          flat_amount: 289600,
          flat_amount_decimal: 289600,
          up_to: 8,
        },
        {
          unit_amount: 48000,
          unit_amount_decimal: 48000,
        },
      ],
      tiers_mode: 'graduated',
      usage_type: 'licensed',
    },
    {
      id: 'price_1IvbYZHnywB98SRr7aGleNSS',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622092495,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        description: 'Tourer',
        firstPurchase: '8',
        EqualPlan: 'Tourer-Yearly',
        type: 'orgseat',
        bundleProduct: 'Paid-TourPlan',
      },
      nickname: 'Tourer',
      product: 'prod_FBpUnzhhfVzyra',
      tiers: [
        {
          flat_amount: 28000,
          flat_amount_decimal: 28000,
          up_to: 8,
        },
        {
          unit_amount: 4000,
          unit_amount_decimal: 4000,
        },
      ],
      tiers_mode: 'graduated',
      usage_type: 'licensed',
    },
    {
      id: 'price_1IvaOzHnywB98SRrt0RsRKvs',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622088057,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        description: 'Starter',
        EqualPlan: 'Starter',
        firstPurchase: '2',
        type: 'orgseat',
        bundleProduct: 'Paid-TourPlan-Yearly',
      },
      nickname: 'Starter-Yearly',
      product: 'prod_FBpUnzhhfVzyra',
      tiers: [
        {
          flat_amount: 86000,
          flat_amount_decimal: 86000,
          up_to: 2,
        },
        {
          unit_amount: 60000,
          unit_amount_decimal: 60000,
        },
      ],
      tiers_mode: 'graduated',
      usage_type: 'licensed',
    },
    {
      id: 'price_1IvaMHHnywB98SRrxpxcLhPV',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622087889,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        EqualPlan: 'Starter-Yearly',
        firstPurchase: '2',
        type: 'orgseat',
        bundleProduct: 'Paid-TourPlan',
        description: 'Starter',
      },
      nickname: 'Starter',
      product: 'prod_FBpUnzhhfVzyra',
      tiers: [
        {
          flat_amount: 9000,
          flat_amount_decimal: 9000,
          up_to: 2,
        },
        {
          unit_amount: 5000,
          unit_amount_decimal: 5000,
        },
      ],
      tiers_mode: 'graduated',
      usage_type: 'licensed',
    },
    {
      id: 'price_1IvaIBHnywB98SRryQdRYtuZ',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622087635,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        description: 'Traveller',
        EqualPlan: 'Traveller',
        firstPurchase: '4',
        type: 'orgseat',
        bundleProduct: '\nPaid-TourPlan-Yearly',
      },
      nickname: 'Traveller-Yearly',
      product: 'prod_FBpUnzhhfVzyra',
      tiers: [
        {
          flat_amount: 160000,
          flat_amount_decimal: 160000,
          up_to: 4,
        },
        {
          unit_amount: 54000,
          unit_amount_decimal: 54000,
        },
      ],
      tiers_mode: 'graduated',
      usage_type: 'licensed',
    },
    {
      id: 'price_1Iva8qHnywB98SRrIFZshZOT',
      object: 'plan',
      active: true,
      billing_scheme: 'tiered',
      created: 1622087056,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        description: 'Traveller',
        EqualPlan: 'Traveller-Yearly',
        firstPurchase: '4',
        type: 'orgseat',
        bundleProduct: 'Paid-TourPlan',
      },
      nickname: 'Traveller',
      product: 'prod_FBpUnzhhfVzyra',
      tiers: [
        {
          flat_amount: 16000,
          flat_amount_decimal: 16000,
          up_to: 4,
        },
        {
          unit_amount: 4500,
          unit_amount_decimal: 4500,
        },
      ],
      tiers_mode: 'graduated',
      usage_type: 'licensed',
    },
    {
      id: 'plan_GHbiySWqaXUuEu',
      object: 'plan',
      active: true,
      amount: 0,
      amount_decimal: 0,
      billing_scheme: 'per_unit',
      created: 1575245438,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        description: 'Free Tour Seat Plan',
        EqualPlan: 'Free-TourPlan',
        type: 'tourseat',
        productInfo: 'allow you to connect one person as view role per tour',
      },
      nickname: 'Free-TourPlan-Yearly',
      product: 'prod_G9k7tNPy0S4UNh',
      usage_type: 'licensed',
    },
    {
      id: 'plan_GHbevWx3SGd8u9',
      object: 'plan',
      active: true,
      amount: 0,
      amount_decimal: 0,
      billing_scheme: 'per_unit',
      created: 1575245211,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        description: 'Free Tour Seat Plan',
        EqualPlan: 'Free-TourPlan-Yearly',
        type: 'tourseat',
        productInfo: 'allow you to connect one person as view role per tour',
      },
      nickname: 'Free-TourPlan',
      product: 'prod_G9k7tNPy0S4UNh',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FrTSZ56wdkzOfi',
      object: 'plan',
      active: true,
      amount: 0,
      amount_decimal: 0,
      billing_scheme: 'per_unit',
      created: 1569218114,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        EqualPlan: 'Yearly Free',
        description: 'Free',
        type: 'individualseat',
        productInfo: 'allow you to connect one person as viewer role per tour',
      },
      nickname: 'Monthly Free',
      product: 'prod_F6Ywrz6kscSj9h',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FrSMCyWaUp1eBa',
      object: 'plan',
      active: true,
      amount: 19900,
      amount_decimal: 19900,
      billing_scheme: 'per_unit',
      created: 1569214006,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        level: 'top',
        EqualPlan: 'Family & Friends',
        description: 'Family & Friends',
        type: 'individualseat',
        productInfo: 'allow you to connect ten people per tour',
      },
      nickname: 'Family & Friends-Yearly',
      product: 'prod_F6Ywrz6kscSj9h',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FrSLh9dkL1mvMC',
      object: 'plan',
      active: true,
      amount: 2000,
      amount_decimal: 2000,
      billing_scheme: 'per_unit',
      created: 1569213976,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        level: 'top',
        description: 'Family & Friends',
        EqualPlan: 'Family & Friends-Yearly',
        type: 'individualseat',
        productInfo: 'allow you to connect ten people per tour',
      },
      nickname: 'Family & Friends',
      product: 'prod_F6Ywrz6kscSj9h',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FrSKYLOqG9nqkt',
      object: 'plan',
      active: true,
      amount: 15000,
      amount_decimal: 15000,
      billing_scheme: 'per_unit',
      created: 1569213902,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        description: 'Family',
        EqualPlan: 'Family',
        type: 'individualseat',
        productInfo: 'allow you to connect five people per tour',
      },
      nickname: 'Family-Yearly',
      product: 'prod_F6Ywrz6kscSj9h',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FrSJeF0F4rWCBe',
      object: 'plan',
      active: true,
      amount: 1500,
      amount_decimal: 1500,
      billing_scheme: 'per_unit',
      created: 1569213846,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        EqualPlan: 'Family-Yearly',
        description: 'Family',
        type: 'individualseat',
        productInfo: 'allow you to connect five people per tour',
      },
      nickname: 'Family',
      product: 'prod_F6Ywrz6kscSj9h',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FrSHi9VZbSlcDe',
      object: 'plan',
      active: true,
      amount: 9900,
      amount_decimal: 9900,
      billing_scheme: 'per_unit',
      created: 1569213706,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        description: 'Partner',
        EqualPlan: 'Partner',
        type: 'individualseat',
        productInfo: 'allow you to connect two people per tour',
      },
      nickname: 'Partner-Yearly',
      product: 'prod_F6Ywrz6kscSj9h',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FrSGR9BpBcYkuf',
      object: 'plan',
      active: true,
      amount: 900,
      amount_decimal: 900,
      billing_scheme: 'per_unit',
      created: 1569213655,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        description: 'Partner',
        EqualPlan: 'Partner-Yearly',
        type: 'individualseat',
        productInfo: 'allow you to connect two people per tour',
      },
      nickname: 'Partner',
      product: 'prod_F6Ywrz6kscSj9h',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FfqGMf7dUgkQSh',
      object: 'plan',
      active: true,
      amount: 0,
      amount_decimal: 0,
      billing_scheme: 'per_unit',
      created: 1566535260,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        EqualPlan: 'Monthly Free',
        description: 'Free',
        firstPurchase: '0',
        type: 'orgseat',
        bundleProduct: 'Free-TourPlan-Yearly',
      },
      nickname: 'Yearly Free',
      product: 'prod_FBpUnzhhfVzyra',
      usage_type: 'licensed',
    },
    {
      id: 'plan_Fbjr3yReYCTzAG',
      object: 'plan',
      active: true,
      amount: 0,
      amount_decimal: 0,
      billing_scheme: 'per_unit',
      created: 1565588850,
      currency: 'aud',
      interval: 'year',
      interval_count: 1,
      metadata: {
        EqualPlan: 'Monthly Free',
        description: 'Free',
        type: 'individualseat',
        productInfo: 'allow you to connect one person as viewer role per tour',
      },
      nickname: 'Yearly Free',
      product: 'prod_F6Ywrz6kscSj9h',
      usage_type: 'licensed',
    },
    {
      id: 'plan_FH3wkYtKKHT7IP',
      object: 'plan',
      active: true,
      amount: 0,
      amount_decimal: 0,
      billing_scheme: 'per_unit',
      created: 1560820111,
      currency: 'aud',
      interval: 'month',
      interval_count: 1,
      metadata: {
        EqualPlan: 'Yearly Free',
        description: 'Free',
        firstPurchase: '0',
        type: 'orgseat',
        bundleProduct: 'Free-TourPlan',
      },
      nickname: 'Monthly Free',
      product: 'prod_FBpUnzhhfVzyra',
      usage_type: 'licensed',
    },
  ],
  url: '/v1/plans',
};
