export const peopleDataSample = {
  users: [
    {
      id: 23,
      orgId: 475,
      email: 'danlazojr@yahoo.com',
    },
  ],
  persons: [
    {
      userId: 23,
      nodeId: null,
      knownAs: 'Danilo lazo',
      firstName: 'Dani',
      middleName: 'Villareal',
      lastName: 'lazo',
      accountId: null,
      gender: 'male',
      smsAlertsEnabled: false,
      email: 'danlazojr@yahoo.com',
      secondaryEmail: 'dvlazojr@gmail.com',
      birthPlace: 'Bolinao Pangasinan',
      birthDate: '1997-04-26T00:00:00.000Z',
      insurancePolicy: '23232653ddddddaasssss',
      id: 23,
      createdAt: null,
      updatedAt: '2021-01-31T08:04:55.214Z',
      phones: [
        {
          personId: 23,
          type: 'mobile',
          isDefault: true,
          number: '+61222333345',
          id: 78,
        },
        {
          personId: 23,
          type: 'mobile',
          isDefault: false,
          number: '+639209280778',
          id: 73,
        },
        {
          personId: 23,
          type: 'landline',
          isDefault: false,
          number: '+61285350315',
          id: 77,
        },
      ],
      photo: {
        type: 'person',
        url:
          'FileContainers/com.ugroop.personContainer/download/bbdf43fa-d6c9-4366-853b-05d2ef4fc2c9.jpeg',
        x: '0.25634408602150566',
        y: '0',
        w: null,
        h: null,
        width: '0.567741935483871',
        height: '1',
        scale: '1',
        rotate: '0',
        id: 74,
        personId: 23,
        passportId: null,
        documentId: null,
      },
    },
  ],
  organisations: [
    {
      name: 'a da ad sdasda adas',
      namekey: 'tenant.group.org-adaadsdasdaadas-',
      country: 'AUS',
      website: null,
      type: null,
      createdBy: 43,
      lastModifiedBy: 43,
      id: 40,
      typeId: null,
    },
    {
      name: 'orgname1234',
      namekey:
        'tenant.group.org-orgname1234-1112princeshighwayheathmerevictoriaaustralia',
      country: 'AUS',
      website: null,
      type: null,
      createdBy: 44,
      lastModifiedBy: 44,
      id: 41,
      typeId: null,
    },
    {
      name: 'ABC Touring Co',
      namekey: 'org-humanedgecollege-175millsstreetalbertparkvicaustralia',
      country: 'AUS',
      website: null,
      type: 'EducationalInstitution',
      createdBy: 115,
      lastModifiedBy: 115,
      id: 121,
      typeId: 121,
      photo: {
        organisationId: 121,
        url:
          'FileContainers/com.ugroop.personContainer/download/0ddcd441-cfac-45a8-9039-7f51c26a89db.jpeg',
        x: '0.13354492187500006',
        y: '0',
        w: null,
        h: null,
        width: '0.6665039062499999',
        height: '1',
        scale: '1',
        rotate: 0,
        id: 6,
      },
      preference: {
        organisationId: 121,
        country: null,
        timezone: 'Australia/Victoria',
        format: 'ddd, D MMM',
        notes: null,
        reminderFrequencyDays: null,
        reminderAttempts: null,
        reminderDisabled: null,
        paxLabel: 'Guests',
        id: 9,
      },
    },
    {
      name: 'Super Org2',
      namekey: null,
      country: 'AUS',
      website: null,
      type: 'TourProvider',
      createdBy: 4,
      lastModifiedBy: 4,
      id: 218,
      typeId: 218,
    },
    {
      name: 'Mindanao Org',
      namekey: null,
      country: 'AUS',
      website: null,
      type: 'Business',
      createdBy: 23,
      lastModifiedBy: 23,
      id: 475,
      typeId: 475,
    },
    {
      name: 'free org',
      namekey: null,
      country: 'AUS',
      website: null,
      type: 'Business',
      createdBy: 205,
      lastModifiedBy: 205,
      id: 502,
      typeId: 502,
    },
    {
      name: 'ddd',
      namekey: null,
      country: 'AUS',
      website: null,
      type: '',
      createdBy: 4,
      lastModifiedBy: 4,
      id: 503,
      typeId: 503,
    },
  ],
  nodeShares: [
    {
      shareTo: 'danlazojr@yahoo.com',
      shareToUserId: 23,
      shareFrom: 113,
      role: 'tour_organizer',
      status: 'confirmed',
      notificationToken: 'agpoGdwm8T9CuoVZjYPCoiBBLXyQesGp',
      nodeId: 5719,
      content: null,
      resendUserId: 0,
      id: 237,
      createdAt: '2019-04-12T02:44:15.088Z',
      updatedAt: '2019-04-16T08:56:12.262Z',
      subNodes: [],
    },
  ],
  userNodes: [
    {
      nodeId: 5719,
      userId: 23,
      userNodeId: null,
      shareFrom: 113,
      role: 'tour_organizer',
      userRole: null,
      id: 158,
      createdAt: '2019-04-16T08:56:12.259Z',
      updatedAt: '2019-04-16T08:56:12.259Z',
      userNodes: [],
    },
    {
      nodeId: 5719,
      userId: 23,
      userNodeId: null,
      shareFrom: 4,
      role: 'tour_participant',
      userRole: null,
      id: 536,
      createdAt: '2019-12-05T02:13:36.117Z',
      updatedAt: '2019-12-05T02:13:36.117Z',
      userNodes: [
        {
          nodeId: 13867,
          userId: 23,
          userNodeId: 536,
          shareFrom: 4,
          role: 'participant_linkee',
          userRole: null,
          id: 537,
          createdAt: '2019-12-05T02:13:36.128Z',
          updatedAt: '2019-12-05T02:13:36.129Z',
        },
      ],
    },
  ],
};

export const participantDataSample = {
  nodes: [
    {
      content: null,
      status: 'confirmed',
      parentNodeId: 5719,
      type: 'participant',
      sharedWith: null,
      printMode: null,
      createdBy: 4,
      lastModifiedBy: 4,
      id: 13867,
      createdAt: '2019-12-05T02:13:33.463Z',
      updatedAt: '2019-12-05T02:13:33.478Z',
      customData: {
        firstName: 'danilo',
        lastName: 'lazo',
        email: 'danlazojr@yahoo.com',
        dob: '2018-02-14T00:00:00.000Z',
        dobMode: 'user',
        namePersonId: 0,
        personType: null,
        comment: null,
        note: null,
        insuranceMode: null,
        insuranceValue: null,
        primary: false,
        phone: null,
        phoneId: null,
        ageType: null,
        honorificTitle: null,
        roomType: null,
        orgId: 3,
        lastUpdate: '2019-12-05T02:13:33.478Z',
      },
      children: [],
      forms: [],
      calculated: {
        people: [529],
      },
    },
  ],
  people: [
    {
      userId: null,
      nodeId: 13867,
      knownAs: 'danilo lazo',
      firstName: 'danilo',
      middleName: null,
      lastName: 'lazo',
      accountId: null,
      gender: null,
      smsAlertsEnabled: null,
      email: 'danlazojr@yahoo.com',
      secondaryEmail: null,
      birthPlace: null,
      birthDate: '2018-02-14T00:00:00.000Z',
      insurancePolicy: null,
      id: 529,
      createdAt: '2019-12-05T02:13:45.173Z',
      updatedAt: '2019-12-05T02:13:45.174Z',
      phones: [],
      passports: [],
      medicals: [],
      dietaries: [],
      studentDetails: [],
      preferences: [],
      photo: null,
    },
    {
      userId: 23,
      nodeId: null,
      knownAs: 'Danilo lazo',
      firstName: 'Dani',
      middleName: 'Villareal',
      lastName: 'lazo',
      accountId: null,
      gender: 'male',
      smsAlertsEnabled: false,
      email: 'danlazojr@yahoo.com',
      secondaryEmail: 'dvlazojr@gmail.com',
      birthPlace: 'Bolinao Pangasinan',
      birthDate: '1997-04-26T00:00:00.000Z',
      insurancePolicy: '23232653ddddddaasssss',
      id: 23,
      createdAt: null,
      updatedAt: '2021-01-31T08:04:55.214Z',
      phones: [
        {
          personId: 23,
          type: 'mobile',
          isDefault: false,
          number: '+639209280778',
          id: 73,
        },
        {
          personId: 23,
          type: 'landline',
          isDefault: false,
          number: '+61285350315',
          id: 77,
        },
        {
          personId: 23,
          type: 'mobile',
          isDefault: true,
          number: '+61222333345',
          id: 78,
        },
      ],
      passports: [
        {
          personId: 23,
          passportNumber: '1324464',
          passportType: 'regular_passport',
          cardNumber: '',
          countryCode: 'AU',
          lastName: 'Lazo',
          middleName: '',
          firstName: 'Danilo',
          issuingAuthority: '',
          issuedDate: null,
          expireDate: null,
          isDefault: false,
          id: 31,
          createdAt: '2019-12-04T03:40:19.248Z',
          updatedAt: '2020-10-27T13:24:44.573Z',
          photo: {
            type: 'passport',
            url:
              'FileContainers/com.ugroop.personContainer/download/4b63946c-a8f1-4b8e-bd2a-db9766110073.jpeg',
            x: '0.08000000000000002',
            y: '0',
            w: null,
            h: null,
            width: '0.84',
            height: '1',
            scale: '1',
            rotate: '0',
            id: 159,
            personId: 23,
            passportId: 31,
            documentId: null,
          },
        },
        {
          personId: 23,
          passportNumber: '233432412343',
          passportType: 'regular_passport',
          cardNumber: '',
          countryCode: 'AU',
          lastName: '',
          middleName: '',
          firstName: '',
          issuingAuthority: '',
          issuedDate: null,
          expireDate: null,
          isDefault: false,
          id: 37,
          createdAt: '2020-07-27T06:21:49.142Z',
          updatedAt: '2020-07-27T06:21:49.142Z',
          photo: null,
        },
        {
          personId: 23,
          passportNumber: '',
          passportType: 'regular_passport',
          cardNumber: '',
          countryCode: 'AU',
          lastName: '',
          middleName: 'Lazo',
          firstName: 'Dan',
          issuingAuthority: '',
          issuedDate: null,
          expireDate: null,
          isDefault: true,
          id: 41,
          createdAt: '2020-10-27T13:24:28.780Z',
          updatedAt: '2020-10-27T13:24:44.587Z',
          photo: null,
        },
      ],
      medicals: [
        {
          description: 'Allergy',
          severity: 'mild',
          action: 'Take anaphylaxis',
          personId: 23,
          id: 30,
        },
        {
          description: 'Heart Condition',
          severity: 'moderate',
          action: '123125',
          personId: 23,
          id: 37,
        },
        {
          description: 'Love life',
          severity: 'mild',
          action: '',
          personId: 23,
          id: 38,
        },
      ],
      dietaries: [
        {
          description: 'Vitamin C',
          personId: 23,
          id: 27,
        },
      ],
      studentDetails: [],
      preferences: [
        {
          personId: 23,
          key: 'reminderDisabled',
          value: '0',
          id: 10,
        },
        {
          personId: 23,
          key: 'seeMoreDisabled',
          value: '0',
          id: 12,
        },
        {
          personId: 23,
          key: 'reminderAttempts',
          value: '5',
          id: 13,
        },
        {
          personId: 23,
          key: 'reminderFrequencyDays',
          value: '1',
          id: 14,
        },
      ],
      photo: {
        type: 'person',
        url:
          'FileContainers/com.ugroop.personContainer/download/bbdf43fa-d6c9-4366-853b-05d2ef4fc2c9.jpeg',
        x: '0.25634408602150566',
        y: '0',
        w: null,
        h: null,
        width: '0.567741935483871',
        height: '1',
        scale: '1',
        rotate: '0',
        id: 74,
        personId: 23,
        passportId: null,
        documentId: null,
      },
    },
    {
      userId: 23,
      nodeId: null,
      knownAs: 'Danilo lazo',
      firstName: 'Dani',
      middleName: 'Villareal',
      lastName: 'lazo',
      accountId: null,
      gender: 'male',
      smsAlertsEnabled: false,
      email: 'danlazojr@yahoo.com',
      secondaryEmail: 'dvlazojr@gmail.com',
      birthPlace: 'Bolinao Pangasinan',
      birthDate: '1997-04-26T00:00:00.000Z',
      insurancePolicy: '23232653ddddddaasssss',
      id: 23,
      createdAt: null,
      updatedAt: '2021-01-31T08:04:55.214Z',
      phones: [
        {
          personId: 23,
          type: 'mobile',
          isDefault: false,
          number: '+639209280778',
          id: 73,
        },
        {
          personId: 23,
          type: 'landline',
          isDefault: false,
          number: '+61285350315',
          id: 77,
        },
        {
          personId: 23,
          type: 'mobile',
          isDefault: true,
          number: '+61222333345',
          id: 78,
        },
      ],
      passports: [
        {
          personId: 23,
          passportNumber: '1324464',
          passportType: 'regular_passport',
          cardNumber: '',
          countryCode: 'AU',
          lastName: 'Lazo',
          middleName: '',
          firstName: 'Danilo',
          issuingAuthority: '',
          issuedDate: null,
          expireDate: null,
          isDefault: false,
          id: 31,
          createdAt: '2019-12-04T03:40:19.248Z',
          updatedAt: '2020-10-27T13:24:44.573Z',
          photo: {
            type: 'passport',
            url:
              'FileContainers/com.ugroop.personContainer/download/4b63946c-a8f1-4b8e-bd2a-db9766110073.jpeg',
            x: '0.08000000000000002',
            y: '0',
            w: null,
            h: null,
            width: '0.84',
            height: '1',
            scale: '1',
            rotate: '0',
            id: 159,
            personId: 23,
            passportId: 31,
            documentId: null,
          },
        },
        {
          personId: 23,
          passportNumber: '233432412343',
          passportType: 'regular_passport',
          cardNumber: '',
          countryCode: 'AU',
          lastName: '',
          middleName: '',
          firstName: '',
          issuingAuthority: '',
          issuedDate: null,
          expireDate: null,
          isDefault: false,
          id: 37,
          createdAt: '2020-07-27T06:21:49.142Z',
          updatedAt: '2020-07-27T06:21:49.142Z',
          photo: null,
        },
        {
          personId: 23,
          passportNumber: '',
          passportType: 'regular_passport',
          cardNumber: '',
          countryCode: 'AU',
          lastName: '',
          middleName: 'Lazo',
          firstName: 'Dan',
          issuingAuthority: '',
          issuedDate: null,
          expireDate: null,
          isDefault: true,
          id: 41,
          createdAt: '2020-10-27T13:24:28.780Z',
          updatedAt: '2020-10-27T13:24:44.587Z',
          photo: null,
        },
      ],
      medicals: [
        {
          description: 'Allergy',
          severity: 'mild',
          action: 'Take anaphylaxis',
          personId: 23,
          id: 30,
        },
        {
          description: 'Heart Condition',
          severity: 'moderate',
          action: '123125',
          personId: 23,
          id: 37,
        },
        {
          description: 'Love life',
          severity: 'mild',
          action: '',
          personId: 23,
          id: 38,
        },
      ],
      dietaries: [
        {
          description: 'Vitamin C',
          personId: 23,
          id: 27,
        },
      ],
      studentDetails: [],
      preferences: [
        {
          personId: 23,
          key: 'reminderDisabled',
          value: '0',
          id: 10,
        },
        {
          personId: 23,
          key: 'seeMoreDisabled',
          value: '0',
          id: 12,
        },
        {
          personId: 23,
          key: 'reminderAttempts',
          value: '5',
          id: 13,
        },
        {
          personId: 23,
          key: 'reminderFrequencyDays',
          value: '1',
          id: 14,
        },
      ],
      photo: {
        type: 'person',
        url:
          'FileContainers/com.ugroop.personContainer/download/bbdf43fa-d6c9-4366-853b-05d2ef4fc2c9.jpeg',
        x: '0.25634408602150566',
        y: '0',
        w: null,
        h: null,
        width: '0.567741935483871',
        height: '1',
        scale: '1',
        rotate: '0',
        id: 74,
        personId: 23,
        passportId: null,
        documentId: null,
      },
    },
  ],
};
