export const productData = {
  object: 'list',
  data: [
    {
      id: 'prod_G9k7tNPy0S4UNh',
      object: 'product',
      active: true,
      attributes: [],
      created: 1573431619,
      images: [],
      metadata: {},
      name: 'Enterprise-Tour',
      type: 'service',
      updated: 1622529741,
    },
    {
      id: 'prod_FBpUnzhhfVzyra',
      object: 'product',
      active: true,
      attributes: [],
      created: 1559613194,
      images: [],
      metadata: {
        description: 'test',
      },
      name: 'Enterprise',
      type: 'service',
      unit_label: 'seat',
      updated: 1622092838,
    },
    {
      id: 'prod_F6Ywrz6kscSj9h',
      object: 'product',
      active: true,
      attributes: [],
      created: 1558398381,
      images: [],
      metadata: {},
      name: 'Individual',
      type: 'service',
      updated: 1615621569,
    },
  ],
  url: '/v1/products',
};
