export const CustomerData = {
  customers: {
    object: 'list',
    data: [
      {
        id: 'cus_JWV6HWoXIeSXPC',
        object: 'customer',
        account_balance: 0,
        address: null,
        balance: 0,
        created: 1623135937,
        currency: 'aud',
        default_source: null,
        default_source_type: null,
        delinquent: false,
        description: null,
        discount: null,
        email: 'yuy0311+02@gmail.com',
        invoice_prefix: '34BBAC66',
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {
          OrgId: '2',
          UserId: '1',
        },
        name: 'MyLordMyGod',
        phone: null,
        preferred_locales: [],
        shipping: null,
        sources: {
          object: 'list',
          data: [],
          has_more: false,
          url: '/v1/customers/cus_JdFVbY9b1S7jvN/sources',
        },
        subscriptions: {
          object: 'list',
          data: [
            {
              id: 'sub_JdYQIDuTZnA8iM',
              object: 'subscription',
              billing: 'charge_automatically',
              billing_cycle_anchor: 1623206310,
              collection_method: 'charge_automatically',
              created: 1623206310,
              current_period_end: 1625798310,
              current_period_start: 1623206310,
              customer: 'cus_JWV6HWoXIeSXPC',
              default_payment_method: null,
              default_source: null,
              default_tax_rates: [
                {
                  id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
                  object: 'tax_rate',
                  active: true,
                  created: 1559609129,
                  description: 'GST',
                  display_name: 'GST',
                  jurisdiction: 'Australia',
                  metadata: {},
                  percentage: 10,
                },
              ],
              items: {
                object: 'list',
                data: [
                  {
                    id: 'si_JdYQHvpGrtkmik',
                    object: 'subscription_item',
                    created: 1623206311,
                    metadata: {},
                    plan: {
                      id: 'price_1IvaMHHnywB98SRrxpxcLhPV',
                      object: 'plan',
                      active: true,
                      billing_scheme: 'tiered',
                      created: 1622087889,
                      currency: 'aud',
                      interval: 'month',
                      interval_count: 1,
                      metadata: {
                        EqualPlan: 'Starter-Yearly',
                        firstPurchase: '2',
                        type: 'orgseat',
                        bundleProduct: 'Paid-TourPlan',
                        description: 'Starter',
                      },
                      nickname: 'Starter',
                      product: 'prod_FBpUnzhhfVzyra',
                      tiers: [
                        {
                          flat_amount: 9000,
                          flat_amount_decimal: 9000,
                          up_to: 2,
                        },
                        {
                          unit_amount: 5000,
                          unit_amount_decimal: 5000,
                        },
                      ],
                      tiers_mode: 'graduated',
                      usage_type: 'licensed',
                    },
                    quantity: 2,
                    subscription: 'sub_JdYQIDuTZnA8iM',
                    tax_rates: [],
                  },
                  {
                    id: 'si_JdYQqTVJe7dCsJ',
                    object: 'subscription_item',
                    created: 1623206311,
                    metadata: {},
                    plan: {
                      id: 'price_1IxRGgHnywB98SRrrJAKMtNw',
                      object: 'plan',
                      active: true,
                      billing_scheme: 'tiered',
                      created: 1622529602,
                      currency: 'aud',
                      interval: 'month',
                      interval_count: 1,
                      metadata: {
                        description: 'Tour Seat Plan',
                        EqualPlan: 'Paid-TourPlan-Yearly',
                        type: 'tourseat',
                      },
                      nickname: 'Paid-TourPlan',
                      product: 'prod_G9k7tNPy0S4UNh',
                      tiers: [
                        {
                          flat_amount: 0,
                          flat_amount_decimal: 0,
                          unit_amount: 0,
                          unit_amount_decimal: 0,
                          up_to: 20,
                        },
                        {
                          flat_amount: 20000,
                          flat_amount_decimal: 20000,
                          unit_amount: 0,
                          unit_amount_decimal: 0,
                          up_to: 40,
                        },
                        {
                          flat_amount: 29000,
                          flat_amount_decimal: 29000,
                          unit_amount: 0,
                          unit_amount_decimal: 0,
                          up_to: 60,
                        },
                        {
                          flat_amount: 37500,
                          flat_amount_decimal: 37500,
                          unit_amount: 0,
                          unit_amount_decimal: 0,
                          up_to: 80,
                        },
                        {
                          flat_amount: 45000,
                          flat_amount_decimal: 45000,
                          unit_amount: 0,
                          unit_amount_decimal: 0,
                          up_to: 100,
                        },
                        {
                          flat_amount: 99900,
                          flat_amount_decimal: 99900,
                          unit_amount: 0,
                          unit_amount_decimal: 0,
                        },
                      ],
                      tiers_mode: 'volume',
                      usage_type: 'licensed',
                    },
                    quantity: 20,
                    subscription: 'sub_JdYQIDuTZnA8iM',
                    tax_rates: [],
                  },
                ],
                url: '/v1/subscription_items?subscription=sub_JdYQIDuTZnA8iM',
              },
              latest_invoice: 'in_1J0HJKHnywB98SRrcVYM2Fwe',
              metadata: {},
              pending_setup_intent: null,
              schedule: null,
              start: 1623206310,
              start_date: 1623206310,
              status: 'active',
              tax_percent: 10,
            },
          ],
          url: '/v1/subscriptions',
        },
        tax_exempt: 'none',
        tax_ids: {
          object: 'list',
          data: [],
          has_more: false,
          url: '/v1/customers/cus_JdFVbY9b1S7jvN/tax_ids',
        },
        tax_info: null,
        tax_info_verification: null,
      },
    ],
    has_more: true,
    url: '/v1/customers',
  },
};
export const CustomerData2 = {
  customers: {
    object: 'list',
    data: [
      {
        id: 'cus_JjEOpmgLOcKwnO',
        object: 'customer',
        account_balance: 0,
        address: null,
        balance: 0,
        created: 1624515677,
        currency: 'aud',
        default_source: 'card_1J5lw9HnywB98SRr50NOmr1e',
        default_source_type: null,
        delinquent: false,
        description: 'COORDINATE_BASE_URL',
        discount: null,
        email: 'yuy0311+140520211@gmail.com',
        invoice_prefix: '9CB350B2',
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {
          OrgId: '2',
          UserId: '1',
        },
        name: 'Yang Yu',
        phone: null,
        preferred_locales: [],
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1J5lw9HnywB98SRr50NOmr1e',
              object: 'card',
              account: null,
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: '42424',
              address_zip_check: 'pass',
              available_payout_methods: null,
              brand: 'Visa',
              country: 'US',
              currency: null,
              customer: 'cus_JjEOpmgLOcKwnO',
              cvc_check: 'pass',
              default_for_currency: false,
              dynamic_last4: null,
              exp_month: 4,
              exp_year: 2024,
              fingerprint: 'dsjwz73snQNZGnf8',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              recipient: null,
              three_d_secure: null,
              tokenization_method: null,
              description: null,
              iin: null,
              issuer: null,
            },
          ],
          has_more: false,
          url: '/v1/customers/cus_JjEOpmgLOcKwnO/sources',
        },
        subscriptions: {
          object: 'list',
          data: [
            {
              id: 'sub_JjEOg5XFAs92I5',
              object: 'subscription',
              application_fee_percent: null,
              billing: 'charge_automatically',
              billing_cycle_anchor: 1624515678,
              billing_thresholds: null,
              cancel_at: null,
              cancel_at_period_end: false,
              canceled_at: null,
              collection_method: 'charge_automatically',
              created: 1624515678,
              current_period_end: 1656051678,
              current_period_start: 1624515678,
              customer: 'cus_JjEOpmgLOcKwnO',
              days_until_due: null,
              default_payment_method: null,
              default_source: null,
              default_tax_rates: [
                {
                  id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
                  object: 'tax_rate',
                  active: true,
                  created: 1559609129,
                  description: 'GST',
                  display_name: 'GST',
                  inclusive: false,
                  jurisdiction: 'Australia',
                  livemode: false,
                  metadata: {},
                  percentage: 10,
                },
              ],
              discount: null,
              ended_at: null,
              items: {
                object: 'list',
                data: [
                  {
                    id: 'si_JjEOPDUDy8EBFa',
                    object: 'subscription_item',
                    created: 1624515679,
                    metadata: {},
                    plan: {
                      id: 'price_1IvaIBHnywB98SRryQdRYtuZ',
                      object: 'plan',
                      active: true,
                      aggregate_usage: null,
                      amount: null,
                      amount_decimal: null,
                      billing_scheme: 'tiered',
                      created: 1622087635,
                      currency: 'aud',
                      interval: 'year',
                      interval_count: 1,
                      livemode: false,
                      metadata: {
                        description: 'Traveller',
                        EqualPlan: 'Traveller',
                        firstPurchase: '4',
                        type: 'orgseat',
                        bundleProduct: 'Paid-TourPlan-Yearly',
                      },
                      nickname: 'Traveller-Yearly',
                      product: 'prod_FBpUnzhhfVzyra',
                      tiers: [
                        {
                          flat_amount: 160000,
                          flat_amount_decimal: 160000,
                          unit_amount: null,
                          unit_amount_decimal: null,
                          up_to: 4,
                        },
                        {
                          flat_amount: null,
                          flat_amount_decimal: null,
                          unit_amount: 54000,
                          unit_amount_decimal: 54000,
                          up_to: null,
                        },
                      ],
                      tiers_mode: 'graduated',
                      transform_usage: null,
                      trial_period_days: null,
                      usage_type: 'licensed',
                    },
                    quantity: 5,
                    subscription: 'sub_JjEOg5XFAs92I5',
                    tax_rates: [],
                  },
                  {
                    id: 'si_JjEO6dXrmU9kj3',
                    object: 'subscription_item',
                    created: 1624515679,
                    metadata: {},
                    plan: {
                      id: 'price_1IxRIuHnywB98SRrYEIsDSWs',
                      object: 'plan',
                      active: true,
                      aggregate_usage: null,
                      amount: null,
                      amount_decimal: null,
                      billing_scheme: 'tiered',
                      created: 1622529740,
                      currency: 'aud',
                      interval: 'year',
                      interval_count: 1,
                      livemode: false,
                      metadata: {
                        description: 'Tour Seat Plan',
                        EqualPlan: 'Paid-TourPlan',
                        type: 'tourseat',
                      },
                      nickname: 'Paid-TourPlan-Yearly',
                      product: 'prod_G9k7tNPy0S4UNh',
                      tiers: [
                        {
                          flat_amount: 0,
                          flat_amount_decimal: 0,
                          unit_amount: null,
                          unit_amount_decimal: null,
                          up_to: 20,
                        },
                        {
                          flat_amount: 200000,
                          flat_amount_decimal: 200000,
                          unit_amount: null,
                          unit_amount_decimal: null,
                          up_to: 40,
                        },
                        {
                          flat_amount: 290000,
                          flat_amount_decimal: 290000,
                          unit_amount: null,
                          unit_amount_decimal: null,
                          up_to: 60,
                        },
                        {
                          flat_amount: 360000,
                          flat_amount_decimal: 360000,
                          unit_amount: null,
                          unit_amount_decimal: null,
                          up_to: 80,
                        },
                        {
                          flat_amount: 440000,
                          flat_amount_decimal: 440000,
                          unit_amount: null,
                          unit_amount_decimal: null,
                          up_to: 100,
                        },
                        {
                          flat_amount: 999900,
                          flat_amount_decimal: 999900,
                          unit_amount: null,
                          unit_amount_decimal: null,
                          up_to: null,
                        },
                      ],
                      tiers_mode: 'volume',
                      transform_usage: null,
                      trial_period_days: null,
                      usage_type: 'licensed',
                    },
                    quantity: 4,
                    subscription: 'sub_JjEOg5XFAs92I5',
                    tax_rates: [],
                  },
                ],
                has_more: false,
                url: '/v1/subscription_items?subscription=sub_JjEOg5XFAs92I5',
              },
              latest_invoice: 'in_1J5lwBHnywB98SRrsn5ZiQKv',
              livemode: false,
              metadata: {},
              pending_setup_intent: null,
              plan: null,
              quantity: null,
              schedule: null,
              start: 1624515678,
              start_date: 1624515678,
              status: 'active',
              tax_percent: 10,
              transfer_data: null,
              trial_end: null,
              trial_start: null,
            },
          ],
          has_more: false,
          url: '/v1/customers/cus_JjEOpmgLOcKwnO/subscriptions',
        },
        tax_exempt: 'none',
        tax_ids: {
          object: 'list',
          data: [],
          has_more: false,
          url: '/v1/customers/cus_JjEOpmgLOcKwnO/tax_ids',
        },
        tax_info: null,
        tax_info_verification: null,
      },
    ],
    has_more: false,
    url: '/v1/customers',
  },
};
export const CustomerDataFree = {
  customers: {
    object: 'list',
    data: [
      {
        id: 'cus_JjEOpmgLOcKwnO',
        object: 'customer',
        account_balance: 0,
        address: null,
        balance: 0,
        created: 1624515677,
        currency: 'aud',
        default_source: null,
        default_source_type: null,
        delinquent: false,
        description: 'COORDINATE_BASE_URL',
        discount: null,
        email: 'yuy0311+140520211@gmail.com',
        invoice_prefix: '9CB350B2',
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {
          OrgId: '2',
          UserId: '1',
        },
        name: 'Yang Yu',
        phone: null,
        preferred_locales: [],
        shipping: null,
        sources: {
          object: 'list',
          data: [],
          has_more: false,
          url: '/v1/customers/cus_JjEOpmgLOcKwnO/sources',
        },
        subscriptions: {
          object: 'list',
          data: [
            {
              id: 'sub_JdwNlOjSTIPQtt',
              object: 'subscription',
              billing: 'charge_automatically',
              billing_cycle_anchor: 1623295457,
              collection_method: 'charge_automatically',
              created: 1623295457,
              current_period_end: 1625887457,
              current_period_start: 1623295457,
              customer: 'cus_JZ6lW1qrYwmn6Y',
              default_payment_method: null,
              default_source: null,
              default_tax_rates: [
                {
                  id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
                  object: 'tax_rate',
                  active: true,
                  created: 1559609129,
                  description: 'GST',
                  display_name: 'GST',
                  jurisdiction: 'Australia',
                  metadata: {},
                  percentage: 10,
                },
              ],
              items: {
                object: 'list',
                data: [
                  {
                    id: 'si_JdwNPjB4HbSkm7',
                    object: 'subscription_item',
                    created: 1623295457,
                    metadata: {},
                    plan: {
                      id: 'plan_FH3wkYtKKHT7IP',
                      object: 'plan',
                      active: true,
                      amount: 0,
                      amount_decimal: 0,
                      billing_scheme: 'per_unit',
                      created: 1560820111,
                      currency: 'aud',
                      interval: 'month',
                      interval_count: 1,
                      metadata: {
                        EqualPlan: 'Yearly Free',
                        description: 'Free',
                        firstPurchase: '0',
                        type: 'orgseat',
                        bundleProduct: 'Free-TourPlan',
                      },
                      nickname: 'Monthly Free',
                      product: 'prod_FBpUnzhhfVzyra',
                      usage_type: 'licensed',
                    },
                    quantity: 1,
                    subscription: 'sub_JdwNlOjSTIPQtt',
                    tax_rates: [],
                  },
                  {
                    id: 'si_JdwNj4gdps8boz',
                    object: 'subscription_item',
                    created: 1623295457,
                    metadata: {},
                    plan: {
                      id: 'plan_GHbevWx3SGd8u9',
                      object: 'plan',
                      active: true,
                      amount: 0,
                      amount_decimal: 0,
                      billing_scheme: 'per_unit',
                      created: 1575245211,
                      currency: 'aud',
                      interval: 'month',
                      interval_count: 1,
                      metadata: {
                        description: 'Free Tour Seat Plan',
                        EqualPlan: 'Free-TourPlan-Yearly',
                        type: 'tourseat',
                        productInfo:
                          'allow you to connect one person as view role per tour',
                      },
                      nickname: 'Free-TourPlan',
                      product: 'prod_G9k7tNPy0S4UNh',
                      usage_type: 'licensed',
                    },
                    quantity: 1,
                    subscription: 'sub_JdwNlOjSTIPQtt',
                    tax_rates: [],
                  },
                ],
                url: '/v1/subscription_items?subscription=sub_JdwNlOjSTIPQtt',
              },
              latest_invoice: 'in_1J0eVBHnywB98SRrEPcdz8Ha',
              metadata: {},
              pending_setup_intent: null,
              schedule: null,
              start: 1623295457,
              start_date: 1623295457,
              status: 'active',
              tax_percent: 10,
            },
          ],
          url: '/v1/subscriptions',
        },
        tax_exempt: 'none',
        tax_ids: {
          object: 'list',
          data: [],
          has_more: false,
          url: '/v1/customers/cus_JjEOpmgLOcKwnO/tax_ids',
        },
        tax_info: null,
        tax_info_verification: null,
      },
    ],
    has_more: false,
    url: '/v1/customers',
  },
};
