import { StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  root: {},
  grow: {
    flex: '1',
  },
  text: {
    margin: 4,
    fontSize: 12,
    textAlign: 'justify',
    color: 'black',
  },
  header: {
    fontSize: 12,
    textAlign: 'center',
    // color: 'grey',
    backgroundColor: '#faf9f7',
    fontWeight: 700,
    padding: 8,
  },
  reportTitle: {
    fontSize: 15,
    fontWeight: 500,
    color: '#1a2b49',
    textAlign: 'center',
    padding: 2,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 500,
    color: '#1a2b49',
    textAlign: 'left',
    padding: 2,
  },
  label: {
    fontSize: 12,
    textAlign: 'justify',
    color: '#6682a3',
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 2,
    fontWeight: 900,
  },
  field: {
    fontSize: 12,
    textAlign: 'justify',
    color: 'black',
    padding: 2,
  },
  gridRow: {
    flexDirection: 'row',
    display: 'flex',
  },
  headerTop: {
    backgroundColor: '#2b344d',
    paddingTop: 8,
    paddingBottom: 8,
    textAlign: 'center',
    alignItems: 'center',
    width: '100%',
    flexDirection: 'column',
  },
  labelTop: {
    fontSize: 11,
    color: '#e5e7e8',
    padding: 4,
    fontWeight: 900,
    textAlign: 'justify',
  },
  fieldTop: {
    fontSize: 12,
    // color: '#f5f5f3',
    color: '#8ba2bd',
    padding: 4,
    textAlign: 'justify',
  },
  textCenter: {
    textAlign: 'center',
  },
  image: {
    height: 25,
    width: 25,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    borderBottomRightRadius: 50,
    borderBottomLeftRadius: 50,
    // margin: 'auto',
  },
  legendM: {
    color: '#aab20c',
    fontSize: 10,
    textAlign: 'justify',
  },
  legendD: {
    color: '#55cd3d',
    fontSize: 10,
    textAlign: 'justify',
  },
  legend: {
    color: 'black',
    // fontSize: 8,
    textAlign: 'justify',
    // marginTop: 6,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80px',
    height: '10px',
    borderRadius: 10,
    fontSize: 8,
  },
  border: {
    borderTopWidth: 1,
    borderTopColor: '#8898aa',
    borderTopStyle: 'solid',
    borderBottomWidth: 1,
    borderBottomColor: '#8898aa',
    borderBottomStyle: 'solid',
  },
  knob: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '10px',
    height: '10px',
    borderRadius: 10,
    fontSize: 8,
    marginRight: 1,
  },
});

export default styles;
