export const orgSubscription = {
  id: 'cus_JWV6HWoXIeSXPC',
  subscriptions: {
    object: 'list',
    data: [
      {
        id: 'sub_JdYQIDuTZnA8iM',
        object: 'subscription',
        billing: 'charge_automatically',
        billing_cycle_anchor: 1623206310,
        collection_method: 'charge_automatically',
        created: 1623206310,
        current_period_end: 1625798310,
        current_period_start: 1623206310,
        customer: 'cus_JWV6HWoXIeSXPC',
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [
          {
            id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
            object: 'tax_rate',
            active: true,
            created: 1559609129,
            description: 'GST',
            display_name: 'GST',
            jurisdiction: 'Australia',
            metadata: {},
            percentage: 10,
          },
        ],
        items: {
          object: 'list',
          data: [
            {
              id: 'si_JdYQHvpGrtkmik',
              object: 'subscription_item',
              created: 1623206311,
              metadata: {},
              plan: {
                id: 'price_1IvaMHHnywB98SRrxpxcLhPV',
                object: 'plan',
                active: true,
                billing_scheme: 'tiered',
                created: 1622087889,
                currency: 'aud',
                interval: 'month',
                interval_count: 1,
                metadata: {
                  EqualPlan: 'Starter-Yearly',
                  firstPurchase: '2',
                  type: 'orgseat',
                  bundleProduct: 'Paid-TourPlan',
                  description: 'Starter',
                },
                nickname: 'Starter',
                product: 'prod_FBpUnzhhfVzyra',
                tiers: [
                  {
                    flat_amount: 9000,
                    flat_amount_decimal: 9000,
                    up_to: 2,
                  },
                  {
                    unit_amount: 5000,
                    unit_amount_decimal: 5000,
                  },
                ],
                tiers_mode: 'graduated',
                usage_type: 'licensed',
              },
              quantity: 2,
              subscription: 'sub_JdYQIDuTZnA8iM',
              tax_rates: [],
            },
            {
              id: 'si_JdYQqTVJe7dCsJ',
              object: 'subscription_item',
              created: 1623206311,
              metadata: {},
              plan: {
                id: 'price_1IxRGgHnywB98SRrrJAKMtNw',
                object: 'plan',
                active: true,
                billing_scheme: 'tiered',
                created: 1622529602,
                currency: 'aud',
                interval: 'month',
                interval_count: 1,
                metadata: {
                  description: 'Tour Seat Plan',
                  EqualPlan: 'Paid-TourPlan-Yearly',
                  type: 'tourseat',
                },
                nickname: 'Paid-TourPlan',
                product: 'prod_G9k7tNPy0S4UNh',
                tiers: [
                  {
                    flat_amount: 0,
                    flat_amount_decimal: 0,
                    unit_amount: 0,
                    unit_amount_decimal: 0,
                    up_to: 20,
                  },
                  {
                    flat_amount: 20000,
                    flat_amount_decimal: 20000,
                    unit_amount: 0,
                    unit_amount_decimal: 0,
                    up_to: 40,
                  },
                  {
                    flat_amount: 29000,
                    flat_amount_decimal: 29000,
                    unit_amount: 0,
                    unit_amount_decimal: 0,
                    up_to: 60,
                  },
                  {
                    flat_amount: 37500,
                    flat_amount_decimal: 37500,
                    unit_amount: 0,
                    unit_amount_decimal: 0,
                    up_to: 80,
                  },
                  {
                    flat_amount: 45000,
                    flat_amount_decimal: 45000,
                    unit_amount: 0,
                    unit_amount_decimal: 0,
                    up_to: 100,
                  },
                  {
                    flat_amount: 99900,
                    flat_amount_decimal: 99900,
                    unit_amount: 0,
                    unit_amount_decimal: 0,
                  },
                ],
                tiers_mode: 'volume',
                usage_type: 'licensed',
              },
              quantity: 20,
              subscription: 'sub_JdYQIDuTZnA8iM',
              tax_rates: [],
            },
          ],
          url: '/v1/subscription_items?subscription=sub_JdYQIDuTZnA8iM',
        },
        latest_invoice: 'in_1J0HJKHnywB98SRrcVYM2Fwe',
        metadata: {},
        pending_setup_intent: null,
        schedule: null,
        start: 1623206310,
        start_date: 1623206310,
        status: 'active',
        tax_percent: 10,
      },
    ],
    url: '/v1/subscriptions',
  },
};
export const freeOrgSubscription = {
  id: 'cus_JZ6lW1qrYwmn6Y',
  subscriptions: {
    object: 'list',
    data: [
      {
        id: 'sub_JdwNlOjSTIPQtt',
        object: 'subscription',
        billing: 'charge_automatically',
        billing_cycle_anchor: 1623295457,
        collection_method: 'charge_automatically',
        created: 1623295457,
        current_period_end: 1625887457,
        current_period_start: 1623295457,
        customer: 'cus_JZ6lW1qrYwmn6Y',
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [
          {
            id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
            object: 'tax_rate',
            active: true,
            created: 1559609129,
            description: 'GST',
            display_name: 'GST',
            jurisdiction: 'Australia',
            metadata: {},
            percentage: 10,
          },
        ],
        items: {
          object: 'list',
          data: [
            {
              id: 'si_JdwNPjB4HbSkm7',
              object: 'subscription_item',
              created: 1623295457,
              metadata: {},
              plan: {
                id: 'plan_FH3wkYtKKHT7IP',
                object: 'plan',
                active: true,
                amount: 0,
                amount_decimal: 0,
                billing_scheme: 'per_unit',
                created: 1560820111,
                currency: 'aud',
                interval: 'month',
                interval_count: 1,
                metadata: {
                  EqualPlan: 'Yearly Free',
                  description: 'Free',
                  firstPurchase: '0',
                  type: 'orgseat',
                  bundleProduct: 'Free-TourPlan',
                },
                nickname: 'Monthly Free',
                product: 'prod_FBpUnzhhfVzyra',
                usage_type: 'licensed',
              },
              quantity: 1,
              subscription: 'sub_JdwNlOjSTIPQtt',
              tax_rates: [],
            },
            {
              id: 'si_JdwNj4gdps8boz',
              object: 'subscription_item',
              created: 1623295457,
              metadata: {},
              plan: {
                id: 'plan_GHbevWx3SGd8u9',
                object: 'plan',
                active: true,
                amount: 0,
                amount_decimal: 0,
                billing_scheme: 'per_unit',
                created: 1575245211,
                currency: 'aud',
                interval: 'month',
                interval_count: 1,
                metadata: {
                  description: 'Free Tour Seat Plan',
                  EqualPlan: 'Free-TourPlan-Yearly',
                  type: 'tourseat',
                  productInfo:
                    'allow you to connect one person as view role per tour',
                },
                nickname: 'Free-TourPlan',
                product: 'prod_G9k7tNPy0S4UNh',
                usage_type: 'licensed',
              },
              quantity: 1,
              subscription: 'sub_JdwNlOjSTIPQtt',
              tax_rates: [],
            },
          ],
          url: '/v1/subscription_items?subscription=sub_JdwNlOjSTIPQtt',
        },
        latest_invoice: 'in_1J0eVBHnywB98SRrEPcdz8Ha',
        metadata: {},
        pending_setup_intent: null,
        schedule: null,
        start: 1623295457,
        start_date: 1623295457,
        status: 'active',
        tax_percent: 10,
      },
    ],
    url: '/v1/subscriptions',
  },
};
export const personFamilySubscription = {
  id: 'cus_FtVnAdCKf89C3v',
  subscriptions: {
    object: 'list',
    data: [
      {
        id: 'sub_FtVnAjBelNUme7',
        object: 'subscription',
        billing: 'charge_automatically',
        billing_cycle_anchor: 1582236220,
        collection_method: 'charge_automatically',
        created: 1569688083,
        current_period_end: 1624226620,
        current_period_start: 1621548220,
        customer: 'cus_FtVnAdCKf89C3v',
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [
          {
            id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
            object: 'tax_rate',
            active: true,
            created: 1559609129,
            description: 'GST',
            display_name: 'GST',
            jurisdiction: 'Australia',
            metadata: {},
            percentage: 10,
          },
        ],
        items: {
          object: 'list',
          data: [
            {
              id: 'si_GGMZ3qtBYRRbME',
              object: 'subscription_item',
              created: 1574958492,
              metadata: {},
              plan: {
                id: 'plan_FrSJeF0F4rWCBe',
                object: 'plan',
                active: true,
                amount: 1500,
                amount_decimal: 1500,
                billing_scheme: 'per_unit',
                created: 1569213846,
                currency: 'aud',
                interval: 'month',
                interval_count: 1,
                metadata: {
                  EqualPlan: 'Family-Yearly',
                  description: 'Family',
                  type: 'individualseat',
                  productInfo: 'allow you to connect five people per tour',
                },
                nickname: 'Family',
                product: 'prod_F6Ywrz6kscSj9h',
                usage_type: 'licensed',
              },
              quantity: 1,
              subscription: 'sub_FtVnAjBelNUme7',
              tax_rates: [],
            },
          ],
          url: '/v1/subscription_items?subscription=sub_FtVnAjBelNUme7',
        },
        latest_invoice: 'in_1ItK0XHnywB98SRrPa6ROts2',
        metadata: {},
        pending_setup_intent: null,
        plan: {
          id: 'plan_FrSJeF0F4rWCBe',
          object: 'plan',
          active: true,
          amount: 1500,
          amount_decimal: 1500,
          billing_scheme: 'per_unit',
          created: 1569213846,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            EqualPlan: 'Family-Yearly',
            description: 'Family',
            type: 'individualseat',
            productInfo: 'allow you to connect five people per tour',
          },
          nickname: 'Family',
          product: 'prod_F6Ywrz6kscSj9h',
          usage_type: 'licensed',
        },
        quantity: 1,
        schedule: null,
        start: 1622690851,
        start_date: 1569688083,
        status: 'active',
        tax_percent: 10,
      },
    ],
    url: '/v1/subscriptions',
  },
};
export const freePersonalSubscriptions = {
  id: 'cus_GFlHkRVcdvIrUU',
  subscriptions: {
    object: 'list',
    data: [
      {
        id: 'sub_JaDbTT40LYk98D',
        object: 'subscription',
        billing: 'charge_automatically',
        billing_cycle_anchor: 1622436926,
        collection_method: 'charge_automatically',
        created: 1622436926,
        current_period_end: 1625028926,
        current_period_start: 1622436926,
        customer: 'cus_GFlHkRVcdvIrUU',
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [
          {
            id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
            object: 'tax_rate',
            active: true,
            created: 1559609129,
            description: 'GST',
            display_name: 'GST',
            jurisdiction: 'Australia',
            metadata: {},
            percentage: 10,
          },
        ],
        items: {
          object: 'list',
          data: [
            {
              id: 'si_JaDbbeRFCHk0HK',
              object: 'subscription_item',
              created: 1622436927,
              metadata: {},
              plan: {
                id: 'plan_FrTSZ56wdkzOfi',
                object: 'plan',
                active: true,
                amount: 0,
                amount_decimal: 0,
                billing_scheme: 'per_unit',
                created: 1569218114,
                currency: 'aud',
                interval: 'month',
                interval_count: 1,
                metadata: {
                  EqualPlan: 'Yearly Free',
                  description: 'Free',
                  type: 'individualseat',
                  productInfo:
                    'allow you to connect one person as viewer role per tour',
                },
                nickname: 'Monthly Free',
                product: 'prod_F6Ywrz6kscSj9h',
                usage_type: 'licensed',
              },
              quantity: 1,
              subscription: 'sub_JaDbTT40LYk98D',
              tax_rates: [],
            },
          ],
          url: '/v1/subscription_items?subscription=sub_JaDbTT40LYk98D',
        },
        latest_invoice: 'in_1Ix39uHnywB98SRrUfjNkF8u',
        metadata: {},
        pending_setup_intent: null,
        plan: {
          id: 'plan_FrTSZ56wdkzOfi',
          object: 'plan',
          active: true,
          amount: 0,
          amount_decimal: 0,
          billing_scheme: 'per_unit',
          created: 1569218114,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            EqualPlan: 'Yearly Free',
            description: 'Free',
            type: 'individualseat',
            productInfo:
              'allow you to connect one person as viewer role per tour',
          },
          nickname: 'Monthly Free',
          product: 'prod_F6Ywrz6kscSj9h',
          usage_type: 'licensed',
        },
        quantity: 1,
        schedule: null,
        start: 1622436926,
        start_date: 1622436926,
        status: 'active',
        tax_percent: 10,
      },
    ],
    url: '/v1/subscriptions',
  },
};
export const customerWithoutSubscription = {
  id: 'cus_GFlHkRVcdvIrUU',
  subscriptions: {
    object: 'list',
    data: [],
  },
};
export const travellerYearSubscription = {
  id: 'cus_JjEOpmgLOcKwnO',
  subscriptions: {
    object: 'list',
    data: [
      {
        id: 'sub_JjEOg5XFAs92I5',
        object: 'subscription',
        billing: 'charge_automatically',
        billing_cycle_anchor: 1624515678,
        collection_method: 'charge_automatically',
        created: 1624515678,
        current_period_end: 1656051678,
        current_period_start: 1624515678,
        customer: 'cus_JjEOpmgLOcKwnO',
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [
          {
            id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
            object: 'tax_rate',
            active: true,
            created: 1559609129,
            description: 'GST',
            display_name: 'GST',
            jurisdiction: 'Australia',
            metadata: {},
            percentage: 10,
          },
        ],
        items: {
          object: 'list',
          data: [
            {
              id: 'si_JjEOPDUDy8EBFa',
              object: 'subscription_item',
              created: 1624515679,
              metadata: {},
              plan: {
                id: 'price_1IvaIBHnywB98SRryQdRYtuZ',
                object: 'plan',
                active: true,
                billing_scheme: 'tiered',
                created: 1622087635,
                currency: 'aud',
                interval: 'year',
                interval_count: 1,
                metadata: {
                  description: 'Traveller',
                  EqualPlan: 'Traveller',
                  firstPurchase: '4',
                  type: 'orgseat',
                  bundleProduct: 'Paid-TourPlan-Yearly',
                },
                nickname: 'Traveller-Yearly',
                product: 'prod_FBpUnzhhfVzyra',
                tiers: [
                  {
                    flat_amount: 160000,
                    flat_amount_decimal: 160000,
                    up_to: 4,
                  },
                  {
                    unit_amount: 54000,
                    unit_amount_decimal: 54000,
                  },
                ],
                tiers_mode: 'graduated',
                usage_type: 'licensed',
              },
              quantity: 5,
              subscription: 'sub_JjEOg5XFAs92I5',
              tax_rates: [],
            },
            {
              id: 'si_JjEO6dXrmU9kj3',
              object: 'subscription_item',
              created: 1624515679,
              metadata: {},
              plan: {
                id: 'price_1IxRIuHnywB98SRrYEIsDSWs',
                object: 'plan',
                active: true,
                billing_scheme: 'tiered',
                created: 1622529740,
                currency: 'aud',
                interval: 'year',
                interval_count: 1,
                metadata: {
                  description: 'Tour Seat Plan',
                  EqualPlan: 'Paid-TourPlan',
                  type: 'tourseat',
                },
                nickname: 'Paid-TourPlan-Yearly',
                product: 'prod_G9k7tNPy0S4UNh',
                tiers: [
                  {
                    flat_amount: 0,
                    flat_amount_decimal: 0,
                    up_to: 20,
                  },
                  {
                    flat_amount: 200000,
                    flat_amount_decimal: 200000,
                    up_to: 40,
                  },
                  {
                    flat_amount: 290000,
                    flat_amount_decimal: 290000,
                    up_to: 60,
                  },
                  {
                    flat_amount: 360000,
                    flat_amount_decimal: 360000,
                    up_to: 80,
                  },
                  {
                    flat_amount: 440000,
                    flat_amount_decimal: 440000,
                    up_to: 100,
                  },
                  {
                    flat_amount: 999900,
                    flat_amount_decimal: 999900,
                  },
                ],
                tiers_mode: 'volume',
                usage_type: 'licensed',
              },
              quantity: 4,
              subscription: 'sub_JjEOg5XFAs92I5',
              tax_rates: [],
            },
          ],
          url: '/v1/subscription_items?subscription=sub_JjEOg5XFAs92I5',
        },
        latest_invoice: 'in_1J5lwBHnywB98SRrsn5ZiQKv',
        metadata: {},
        pending_setup_intent: null,
        schedule: null,
        start: 1624515678,
        start_date: 1624515678,
        status: 'active',
        tax_percent: 10,
      },
    ],
    url: '/v1/subscriptions',
  },
};
