// region Endpoints (maps to AccountService endpoints)
export const FILE_CONTAINER_API = 'FileContainers';
export const NODE_API = 'Nodes';
export const FOLDER_API = 'Folders';
export const INVITATION_API = 'Invitations';
export const PUB_API = 'Pub';
export const TEMPLATE_API = 'Templates';
export const USER_API = 'Users';
export const ABILITY_API = 'Abilities';
export const ORGANISATION_API = 'Organisations';
export const NODE_SHARE_API = 'NodeShares';
export const ORG_INVITATION_API = 'OrgInvitations';
export const PERSON_DETAIL_API = 'PersonDetails';
export const FILE_STORE = 'fileDataStore';
export const ORG_INVITATION = 'OrgInvitations';
export const TEMPLATE_TAB_API = 'TemplateTabs';
export const NOTIFICATION_API = 'Notifications';
export const EVENTS_API = 'Events';
export const PLAN_API = 'Plans';
export const PRODUCT_API = 'Products';
export const SUBSCRIPTION_API = 'Subscriptions';
export const SUBSCRIPTION_SCHEDULE_API = 'SubscriptionSchedules';
export const CUSTOMER_API = 'Customers';
export const CARDS_API = 'Cards';
export const PAYMENT_METHOD_API = 'PaymentMethods';
export const INVOICE_API = 'Invoices';
export const CHARGES_API = 'Charges';
export const COUPON_API = 'Coupons';
export const MARKET_API = 'Markets';
// endregion

// region Requests (maps to AccountService model methods)
export const BATCH_MOVE = 'batchMove'; // PUT    /:id/batchMove
export const MOVE_AFTER = 'moveAfter'; // PUT    /:id/moveAfter/:toBeMovedId
export const MOVE_BEFORE = 'moveBefore'; // PUT    /:id/moveBefore:toBeMovedId
export const GET_TOKEN = 'getToken'; // GET    /:tokenId
export const FETCH_EVENTS = 'fetchEvents'; // GET    /:id/events
export const CREATE_EVENT = 'createEvent'; // POST   /:id/event
export const PATCH_EVENT = 'patchEvent'; // PATCH  /:id/event/:eventId
export const DELETE_EVENT = 'deleteEvent'; // DELETE /:id/event/:eventNodeId
export const CREATE_FLIGHT_BOOKING = 'createFlightBooking'; // POST /:id/flightBooking
export const PATCH_FLIGHT_BOOKING = 'patchFlightBooking'; // PATCH  /:id/flightBooking/:bid
export const DELETE_FLIGHT_BOOKING = 'deleteFlightBooking'; // DELETE /:id/flightBooking/:bid

export const GET_PUB_TEMPLATE_TIMES = 'getPubTemplateTimes'; // GET /Pub/template/:hashkey/times
export const GET_PUB_TEMPLATE_TREE = 'getPubTemplateTree'; // GET /Pub/template/:hashkey/tree
export const GET_PUB_TEMPLATE_EVENTS = 'getPubTemplateEvents'; // GET /Pub/template/:hashkey/events
export const GET_PUB_TEMPLATE_PEOPLE = 'getPubTemplatePeople'; // GET /Pub/template/:hashkey/people
export const GET_PUB_TEMPLATE_HEADER = 'getTemplateHeader'; // GET /Pub/template/:hashkey
export const GET_PUB_TEMPLATE_TAB = 'getTemplateTab';
export const BATCH_GET_PUB_TEMPLATE_TAB = 'batchGetTemplateTab';
export const PUB_CREATE_INTEREST = 'pubCreateInterest'; // GET /Pub/interest

export const SHARE_NODE = 'shareNode';
export const GET_PEOPLE = 'findPeople';
export const GET_PERSON = 'getPerson';
export const BATCH_RECENT_ACTIVITY = 'batchRecentActivity';
export const GET_ORGANISATION_MEMBER_INFO = 'getOrganisationMemberInfo';
export const CREATE_CLONE = 'createClone';
export const GET_TIMES = 'getTimes'; // GET /nodes/:id/times
export const GET_TREE = 'getTree'; // GET /Node/:id/tree
export const BATCH_CREATE_CLONE = 'batchCreateClone';
export const GET_NODES_VIA_FILTER = 'getFilterNodes'; // This is the temporal end point, subject to change
export const FIND_PARTICIPANT = 'findParticipant'; // This is the temporal end point, subject to change

export const GET_OWN_ORG_INFO = 'getOwnOrgInfo';
export const CREATE_ORG_USER = 'createOrgUser'; // POST /:users
export const CREATE_USER_VIA_INVITE = 'createUserViaInvite'; // POST /:users
export const SIGN_IN = 'signIn'; // POST /:users/signIn
export const SIGN_OUT = 'signOut'; // POST /:users/signIn
export const FORGET_PWD = 'forgetPassword';
export const RESET_PWD = 'resetPassword';
export const CHANGE_PWD = 'changePassword';
export const RESEND_SIGNUP = 'resendSignUp';
export const ME = 'ME'; // POST /:users/Me
export const PERSON_SYNC = 'userFirstTimeSetup'; // POST /:users/id/firstTimeSetup
export const HIDE_RECENT_ACTIVITY = 'hideRecentActivity'; // PATCH /:users/hideRecentActivity/:nodeId
export const REGISTER_DEVICE = 'registerDevice';
export const UNREGISTER_DEVICE = 'unregisterDevice';
export const UPLOAD_FILE = 'uploadFile'; // POST   /:container/upload
export const FIND_MY_ABILITIES = 'findMyAbilities';
export const FIND_MY_TOURS = 'findMyTours';
export const CHANGE_ROLE = 'changeRole';
export const ADD_ROLE = 'addRole';
export const GET_INVITATIONS = 'getInvitations';
export const GET_ORGANISATION_INVITATIONS = 'getOrganisationInvitations';
export const CONFIRM_INVITATION = 'confirmInvitation';
export const DECLINE_INVITATION = 'declineInvitation';
export const REMOVE_PHOTO = 'removePhoto';
export const DESTROY_FILE = 'destroyFile';
export const CANCEL_INVITATION = 'cancelInvitation';
export const RESEND_INVITATION = 'resendInvitation';
export const GET_RECENT_ACTIVITY = 'recentActivity';
export const GET_PARENT_OF_FOLDER = 'getParentOfFolder'; // GET /Folders/:id/parents
export const GET_FOLDER_CHILDREN_WITH_PAGINATION =
  'getFolderChildrenWithPagination'; // GET /Folders/:id/children
export const CREATE_NODE = 'createNode'; // POST /Node
export const REMOVE_NODE = 'removeNode'; // DELETE /Node/:id
export const UPDATE_NODE = 'updateNode'; // PATCH /Nodes/:id
export const DELETE_CHILDREN_FROM_FOLDER = 'deleteChildrenFromFolder'; // DELETE /Folders/:id
export const REMOVE_TEMPLATE = 'removeTemplate'; // DELETE /Template/:id
export const BATCH_DELETE = 'batchDeleteNode'; // This is multiple request for DELETE /Template/:id
export const BATCH_DELETE_CHILDREN = 'batchDeleteChildren';
export const CREATE_CHILD = 'createChild';
export const CREATE_NEXT_NODE = 'createNextNode';
export const DELETE_CHILDREN = 'deleteChildren';
export const MOVE = 'move'; // PATCH /Nodes/:id/move
export const COPY = 'copyNode'; // POST /Nodes/:id/copy
export const GET_FOLDER_TREE = 'getFolderTree'; // GET /Folders/:id/tree
export const BATCH_GET_FOLDER_TREE = 'batchGetFolderTree'; // GET /Folders/:id/tree but batch
export const GET_ORG_TYPES = 'getOrgTypes';
export const GET_ORG_INFO = 'getOrgInfo';
export const PATCH_ORG = 'patchOrg';
export const ORG_SYNC = 'firstTimeSetup';
export const CREATE_PERSON_FACADE = 'createPersonFacade';
export const GET_PERSON_DETAIL = 'getPersonDetail';
export const PATCH_PERSON_FACADE = 'patchPersonFacade';
export const UPDATE_PERSON = 'updatePerson';
export const GET_ROLES = 'getRoles';
export const CREATE_FEEDBACK = 'createFeedback';
export const CREATE_COMMENT = 'createComment';
export const GET_ORG_MEMBERS = 'getOrgMembers';
export const GET_ORGANISATION = 'getOrganisation';
export const GET_ORG_SUBTYPES = 'getOrgSubtypes';
export const UPDATE_ORG_ROLE = 'updateOrgRole';
export const REMOVE_PHONE = 'removePhone';
export const ADD_PHONE = 'addPhone';
export const PATCH_PHONE = 'patchPhone';
export const UPDATE_ORG_MEMBER = 'updateOrgMember';
export const DELETE_ORG_MEMBER = 'deleteOrgMember';
export const REMOVE_PASSPORT = 'removePassport';
export const ADD_PASSPORT = 'addPassport';
export const PATCH_PASSPORT = 'patchPassport';
export const GET_PASSPORTS_FACADE = 'getPassportsFacade';
export const REMOVE_PASSPORT_FACADE = 'removePassportFacade';
export const CREATE_PASSPORT_FACADE = 'createPassportFacade';
export const PATCH_PASSPORT_FACADE = 'patchPassportFacade';
export const ADD_MEDICAL = 'addMedical';
export const PATCH_MEDICAL = 'patchMedical';
export const REMOVE_MEDICAL = 'removeMedical';
export const ADD_DIETARY = 'addDietary';
export const PATCH_DIETARY = 'patchDietary';
export const REMOVE_DIETARY = 'removeDietary';
export const ADD_STUDENT_DETAIL = 'addStudentDetail';
export const PATCH_STUDENT_DETAIL = 'patchStudentDetail';
export const REMOVE_STUDENT_DETAIL = 'removeStudentDetail';
export const SHARE_ORGANISATION = 'shareOrganisation';
export const GET_TEMPLATE_TAB_DETAIL = 'getTemplateTabDetail';
export const BATCH_GET_TEMPLATE_TAB_DETAIL = 'batchGetTemplateTabDetail';
export const GET_NODE = 'getNode';
export const GET_CHILDREN = 'getChildren';
export const UPDATE_CHILD = 'updateChild';
export const INSERT_BEFORE = 'insertBefore';
export const INSERT_AFTER = 'insertAfter';
export const CREATE_PHOTO = 'createPhoto';
export const UPDATE_PHOTO = 'updatePhoto';
export const GET_ATTACHMENT = 'getAttachment';
export const CREATE_ATTACHMENT = 'createAttachment';
export const UPDATE_ATTACHMENT = 'updateAttachment';
export const REMOVE_ATTACHMENT = 'removeAttachment';
export const GET_TEMPLATE_DETAIL = 'getTemplateDetail';
export const GET_TEMPLATE_HASHKEY = 'getTemplateHashkey';
export const GET_TEMPLATE_FEATURED_LIST = 'getTemplateFeaturedList';
export const GET_FOLDER_IMAGE = 'getFolderImage';
export const GET_PHOTOS = 'getPhotos';
export const MOVE_NODE_BEFORE = 'moveNodeBefore';
export const MOVE_NODE_AFTER = 'moveNodeAfter';

export const GET_CHECKLISTS = 'getChecklists';
export const SETUP_TOUR = 'setupTour';
export const SETUP_PERSONAL_TOUR = 'setupPersonalTour';
export const FIND_ORGANISATION_ID = 'findOrganisationId';

export const GET_PLACE_IDS = 'getPlaceIds';
export const GET_LAT_LONG = 'getLatLong';
export const GET_ALL_LAT_LONG = 'getAllLatLong';
export const GEOCODE_API = 'geocodes';
export const GET_GEO_COUNTRY_CODE = 'getGeoCountryCode';
export const GET_GEO_CURRENT_LOCATION = 'getGeoCurrentLocation';

export const CREATE_ORGANISATION = 'createOrganisation';

export const CREATE_EVENT_ATTACHMENT = 'createEventAttachment';
export const DELETE_EVENT_ATTACHMENT = 'deleteEventAttachment';
export const PATCH_EVENT_ATTACHMENT = 'patchEventAttachment';

export const BATCH_GET_ORG_MEMBERS = 'batchGetOrgMembers';
export const INSERT_TEMP_AFTER = 'insertTempAfter';
export const INSERT_TEMP_BEFORE = 'insertTempBefore';
export const DELETE_TEMP_NODE = 'deleteTempNode';
export const REMOVE_USER_FROM_TOUR = 'removeUserFromTour';
export const CREATE_PERSONAL_REGISTRATION = 'createPersonalRegistration';
export const INIT_TEMPLATE_SETTINGS = 'initTemplateSetting';
export const UPSERT_TEMPLATE_SETTING = 'upsertTemplateSetting';
export const UPSERT_TEMPLATE_SETTINGS = 'upsertTemplateSettings';
export const GET_USER_PREFERENCE = 'getUserPreference';
export const UPDATE_USER_PREFERENCE = 'updateUserPreference';
export const GET_UGROOP_NOTIFICATION = 'getUGroopNotifications';
export const UPDATE_UGROOP_NOTIFICATION_STATUS =
  'updateUgroopNotifcationStatus';
export const GET_PARTICIPANTS = 'getParticipants';

export const GET_SHARED_TEMPLATES = 'getSharedTemplates';
export const GET_DAYS = 'getDays';
export const GET_USER_RELATED_TEMPLATES = 'getUserRelatedTemplates';
export const GET_EVENTS_BY_ID = 'getEventsById';

export const GET_PRODUCT_LIST = 'getProductList';
export const GET_PLAN_LIST = 'getPlanList';

export const CREATE_SUBSCRIPTION_FIRSTTIME = 'createSubscriptionFirstTime';
export const GET_CUSTOMER_SUBSCRIPTION = 'getCustomerSubscription';
export const UPDATE_SUBSCRIPTION = 'updateSubscription';
export const CREATE_LINK = 'createLink';
export const UPDATE_LINK = 'updatedLink';
export const DELETE_LINK = 'deleteLink';
export const REMOVE_NODE_AND_LINKS = 'removeNodeAndLinks';
export const UNLINK_NEXT_NODE = 'unlinkNextNode';
export const LINK_NODE = 'linkNode';
export const UNLINK_NODE = 'unlinkNode';
export const ADD_IMAGE_SUCCESS = 'addImageSuccess';
export const GET_LINKS = 'getLinks';
export const GET_USER_NODE = 'getUserNode';
export const UPDATE_HASHKEY = 'updateHashKey';
export const GET_CUSTOMER = 'getCustomer';
export const UPDATE_CUSTOMER = 'updateCustomer';
export const LIST_SUBSCRIPTION_SCHEDULE = 'listSubscriptionSchedule';
export const UPDATE_SUBSCRIPTION_SCHEDULE = 'updateSubscriptionSchedule';
export const CREATE_SUBSCRIPTION_SCHEDULE = 'createSubscriptionSchedule';
export const RELEASE_SUBSCRIPTION_SCHEDULE = 'releaseSubscriptionSchedule';
export const GET_UPCOMING_INVOICE = 'getUpcomingInvoice';
export const GET_UPCOMING_INVOICE_LINE_ITEMS = 'getUpcomingInvoiceLineItems';
export const CREATE_INVOICE = 'createInvoice';
export const GET_INVOICE = 'getInvoice';
export const GET_INVOICE_INVOICE_LINE_ITEMS = 'getInvoiceLineItems';
export const GET_CUSTOMER_CARDS = 'getCustomerCards';
export const CREATE_CUSTOMER_CARD = 'createCustomerCard';
export const UPDATE_CUSTOMER_CARD = 'updateCustomerCard';
export const DELETE_CUSTOMER_CARD = 'deleteCustomerCard';
export const UPDATE_PAYMENT_METHOD = 'updatePaymentMethod';
export const GET_CUSTOMER_CHARGES = 'getCustomerCharges';
export const GET_COUPON = 'getCoupon';
export const TRANSFER_NODE = 'transfer';
export const GET_TRANSFER_NODE = 'getTransfer';
export const PATCH_TRANSFER_NODE = 'patchTransferNode';
export const GET_TRANSFER_NODE_LIST = 'getTransferAll';
export const ACCEPT_TOUR_OWNERSHIP = 'acceptOwnerTourOwnership';
export const POST_HASHKEY = 'posthashkey';
export const REMOVE_HASHKEY = 'removehashkey';
export const PATCH_TEMPLATE_CUSTOM_DATA = 'patchTemplateCustomData';
export const LIST_TEMPLATE_CUSTOM_DATA = 'listTemplateCustomData';
export const EMAIL_ME_EVENT_ADDRESS = 'emailMeEventAddress';
export const CHANGE_CUSTOM_USER_ROLE = 'changeCustomUserRole';
export const CLONE_PARTICIPANT = 'cloneParticipant';
export const MOVE_NODE_CHILD = 'moveChild';
export const WHATS_NEW = 'whatsNew';
// endregion

export const GET_DETAILS = 'getDetails';

// personal preferences
export const GET_PERSONAL_PREFERENCES = 'getPersonalPreferences';
export const UPSERT_PERSONAL_PREFERENCES = 'upsertPersonalPreferences';

// Market
export const USE_TEMPLATE = 'useTemplate';
export const GET_PUBLISHER_IDS = 'getListPublisherInfo';

export const ADD_MY_OWN_ROLE = 'addMyOwnRole';

export const ADD_INSURANCE_POLICY = 'addInsurancePolicy';
export const PATCH_INSURANCE_POLICY = 'patchInsurancePolicy';
export const REMOVE_INSURANCE_POLICY = 'removeInsurancePolicy';
