export const InvoiceStarterData = {
  object: 'invoice',
  account_country: 'AU',
  account_name: 'uGroop Pty. Ltd.',
  amount_due: 9900,
  amount_remaining: 9900,
  billing: 'charge_automatically',
  billing_reason: 'upcoming',
  charge: null,
  collection_method: 'charge_automatically',
  created: 1627022985,
  currency: 'aud',
  customer: 'cus_JWV6HWoXIeSXPC',
  customer_email: 'yuy0311+140520211@gmail.com',
  customer_name: 'Yang Yu',
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [
    {
      id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
      object: 'tax_rate',
      active: true,
      created: 1559609129,
      description: 'GST',
      display_name: 'GST',
      jurisdiction: 'Australia',
      metadata: {},
      percentage: 10,
    },
  ],
  ending_balance: 0,
  lines: {
    object: 'list',
    data: [
      {
        id: 'sli_140f17HnywB98SRr67415739',
        object: 'line_item',
        currency: 'aud',
        description: '2 seat × Enterprise (Tier 1 at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1627022985,
          end: 1629701385,
        },
        plan: {
          id: 'price_1IvaMHHnywB98SRrxpxcLhPV',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622087889,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            EqualPlan: 'Starter-Yearly',
            firstPurchase: '2',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
            description: 'Starter',
          },
          nickname: 'Starter',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 9000,
              flat_amount_decimal: 9000,
              up_to: 2,
            },
            {
              unit_amount: 5000,
              unit_amount_decimal: 5000,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 2,
        subscription: 'sub_JirdFQfES6fMQG',
        subscription_item: 'si_Jirdx33Dc8HdgT',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_15b9cdHnywB98SRr432695e9',
        object: 'line_item',
        amount: 9000,
        currency: 'aud',
        description: 'Enterprise (Tier 1 at $90.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1627022985,
          end: 1629701385,
        },
        plan: {
          id: 'price_1IvaMHHnywB98SRrxpxcLhPV',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622087889,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            EqualPlan: 'Starter-Yearly',
            firstPurchase: '2',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
            description: 'Starter',
          },
          nickname: 'Starter',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 9000,
              flat_amount_decimal: 9000,
              up_to: 2,
            },
            {
              unit_amount: 5000,
              unit_amount_decimal: 5000,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 0,
        subscription: 'sub_JirdFQfES6fMQG',
        subscription_item: 'si_Jirdx33Dc8HdgT',
        tax_amounts: [
          {
            amount: 900,
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_16fb43HnywB98SRra1554e29',
        object: 'line_item',
        currency: 'aud',
        description: '2 × Enterprise-Tour (Tier 1 at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1627022985,
          end: 1629701385,
        },
        plan: {
          id: 'price_1IxRGgHnywB98SRrrJAKMtNw',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622529602,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Tour Seat Plan',
            EqualPlan: 'Paid-TourPlan-Yearly',
            type: 'tourseat',
          },
          nickname: 'Paid-TourPlan',
          product: 'prod_G9k7tNPy0S4UNh',
          tiers: [
            {
              flat_amount: 0,
              flat_amount_decimal: 0,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 20,
            },
            {
              flat_amount: 20000,
              flat_amount_decimal: 20000,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 40,
            },
            {
              flat_amount: 29000,
              flat_amount_decimal: 29000,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 60,
            },
            {
              flat_amount: 37500,
              flat_amount_decimal: 37500,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 80,
            },
            {
              flat_amount: 45000,
              flat_amount_decimal: 45000,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 100,
            },
            {
              flat_amount: 99900,
              flat_amount_decimal: 99900,
              unit_amount: 0,
              unit_amount_decimal: 0,
            },
          ],
          tiers_mode: 'volume',
          usage_type: 'licensed',
        },
        quantity: 2,
        subscription: 'sub_JirdFQfES6fMQG',
        subscription_item: 'si_JirdEDa0hKPjy4',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_101a7bHnywB98SRrfbcf72fe',
        object: 'line_item',
        currency: 'aud',
        description: 'Enterprise-Tour (Tier 1 at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1627022985,
          end: 1629701385,
        },
        plan: {
          id: 'price_1IxRGgHnywB98SRrrJAKMtNw',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622529602,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Tour Seat Plan',
            EqualPlan: 'Paid-TourPlan-Yearly',
            type: 'tourseat',
          },
          nickname: 'Paid-TourPlan',
          product: 'prod_G9k7tNPy0S4UNh',
          tiers: [
            {
              flat_amount: 0,
              flat_amount_decimal: 0,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 20,
            },
            {
              flat_amount: 20000,
              flat_amount_decimal: 20000,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 40,
            },
            {
              flat_amount: 29000,
              flat_amount_decimal: 29000,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 60,
            },
            {
              flat_amount: 37500,
              flat_amount_decimal: 37500,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 80,
            },
            {
              flat_amount: 45000,
              flat_amount_decimal: 45000,
              unit_amount: 0,
              unit_amount_decimal: 0,
              up_to: 100,
            },
            {
              flat_amount: 99900,
              flat_amount_decimal: 99900,
              unit_amount: 0,
              unit_amount_decimal: 0,
            },
          ],
          tiers_mode: 'volume',
          usage_type: 'licensed',
        },
        quantity: 0,
        subscription: 'sub_JirdFQfES6fMQG',
        subscription_item: 'si_JirdEDa0hKPjy4',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
    ],
    url:
      '/v1/invoices/upcoming/lines?customer=cus_JirdG0lzXbsJ3P&subscription=sub_JirdFQfES6fMQG',
  },
  metadata: {},
  next_payment_attempt: 1627026585,
  number: '7F6CD702-0002',
  payment_intent: null,
  period_end: 1627022985,
  period_start: 1624430985,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  status: 'draft',
  status_transitions: {},
  subscription: 'sub_JirdFQfES6fMQG',
  subtotal: 9000,
  tax: 900,
  tax_percent: 10,
  total_tax_amounts: [
    {
      amount: 900,
      tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
    },
  ],
  total: 9900,
};
export const InvoiceTravellerData = {
  object: 'invoice',
  account_country: 'AU',
  account_name: 'uGroop Pty. Ltd.',
  amount_due: 176000,
  amount_remaining: 176000,
  billing: 'charge_automatically',
  billing_reason: 'upcoming',
  charge: null,
  collection_method: 'charge_automatically',
  created: 1656051678,
  currency: 'aud',
  customer: 'cus_JjEOpmgLOcKwnO',
  customer_email: 'yuy0311+140520211@gmail.com',
  customer_name: 'Yang Yu',
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [
    {
      id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
      object: 'tax_rate',
      active: true,
      created: 1559609129,
      description: 'GST',
      display_name: 'GST',
      jurisdiction: 'Australia',
      metadata: {},
      percentage: 10,
    },
  ],
  ending_balance: 0,
  lines: {
    object: 'list',
    data: [
      {
        id: 'sli_1776abHnywB98SRra9dc7572',
        object: 'line_item',
        currency: 'aud',
        description: '4 seat × Enterprise (Tier 1 at $0.00 / year)',
        discountable: true,
        metadata: {},
        period: {
          start: 1656051678,
          end: 1687587678,
        },
        plan: {
          id: 'price_1IvaIBHnywB98SRryQdRYtuZ',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622087635,
          currency: 'aud',
          interval: 'year',
          interval_count: 1,
          metadata: {
            description: 'Traveller',
            EqualPlan: 'Traveller',
            firstPurchase: '4',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan-Yearly',
          },
          nickname: 'Traveller-Yearly',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 160000,
              flat_amount_decimal: 160000,
              up_to: 4,
            },
            {
              unit_amount: 54000,
              unit_amount_decimal: 54000,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 5,
        subscription: 'sub_JjEOg5XFAs92I5',
        subscription_item: 'si_JjEOPDUDy8EBFa',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_117a0dHnywB98SRr720317d2',
        object: 'line_item',
        amount: 160000,
        currency: 'aud',
        description: 'Enterprise (Tier 1 at $1,600.00 / year)',
        discountable: true,
        metadata: {},
        period: {
          start: 1656051678,
          end: 1687587678,
        },
        plan: {
          id: 'price_1IvaIBHnywB98SRryQdRYtuZ',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622087635,
          currency: 'aud',
          interval: 'year',
          interval_count: 1,
          metadata: {
            description: 'Traveller',
            EqualPlan: 'Traveller',
            firstPurchase: '4',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan-Yearly',
          },
          nickname: 'Traveller-Yearly',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 160000,
              flat_amount_decimal: 160000,
              up_to: 4,
            },
            {
              unit_amount: 54000,
              unit_amount_decimal: 54000,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 0,
        subscription: 'sub_JjEOg5XFAs92I5',
        subscription_item: 'si_JjEOPDUDy8EBFa',
        tax_amounts: [
          {
            amount: 16000,
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_16c497HnywB98SRr0e3aeb0f',
        object: 'line_item',
        currency: 'aud',
        description: '4 × Enterprise-Tour (Tier 1 at $0.00 / year)',
        discountable: true,
        metadata: {},
        period: {
          start: 1656051678,
          end: 1687587678,
        },
        plan: {
          id: 'price_1IxRIuHnywB98SRrYEIsDSWs',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622529740,
          currency: 'aud',
          interval: 'year',
          interval_count: 1,
          metadata: {
            description: 'Tour Seat Plan',
            EqualPlan: 'Paid-TourPlan',
            type: 'tourseat',
          },
          nickname: 'Paid-TourPlan-Yearly',
          product: 'prod_G9k7tNPy0S4UNh',
          tiers: [
            {
              flat_amount: 0,
              flat_amount_decimal: 0,
              up_to: 20,
            },
            {
              flat_amount: 200000,
              flat_amount_decimal: 200000,
              up_to: 40,
            },
            {
              flat_amount: 290000,
              flat_amount_decimal: 290000,
              up_to: 60,
            },
            {
              flat_amount: 360000,
              flat_amount_decimal: 360000,
              up_to: 80,
            },
            {
              flat_amount: 440000,
              flat_amount_decimal: 440000,
              up_to: 100,
            },
            {
              flat_amount: 999900,
              flat_amount_decimal: 999900,
            },
          ],
          tiers_mode: 'volume',
          usage_type: 'licensed',
        },
        quantity: 4,
        subscription: 'sub_JjEOg5XFAs92I5',
        subscription_item: 'si_JjEO6dXrmU9kj3',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_19f646HnywB98SRre4e335d5',
        object: 'line_item',
        currency: 'aud',
        description: 'Enterprise-Tour (Tier 1 at $0.00 / year)',
        discountable: true,
        metadata: {},
        period: {
          start: 1656051678,
          end: 1687587678,
        },
        plan: {
          id: 'price_1IxRIuHnywB98SRrYEIsDSWs',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622529740,
          currency: 'aud',
          interval: 'year',
          interval_count: 1,
          metadata: {
            description: 'Tour Seat Plan',
            EqualPlan: 'Paid-TourPlan',
            type: 'tourseat',
          },
          nickname: 'Paid-TourPlan-Yearly',
          product: 'prod_G9k7tNPy0S4UNh',
          tiers: [
            {
              flat_amount: 0,
              flat_amount_decimal: 0,
              up_to: 20,
            },
            {
              flat_amount: 200000,
              flat_amount_decimal: 200000,
              up_to: 40,
            },
            {
              flat_amount: 290000,
              flat_amount_decimal: 290000,
              up_to: 60,
            },
            {
              flat_amount: 360000,
              flat_amount_decimal: 360000,
              up_to: 80,
            },
            {
              flat_amount: 440000,
              flat_amount_decimal: 440000,
              up_to: 100,
            },
            {
              flat_amount: 999900,
              flat_amount_decimal: 999900,
            },
          ],
          tiers_mode: 'volume',
          usage_type: 'licensed',
        },
        quantity: 0,
        subscription: 'sub_JjEOg5XFAs92I5',
        subscription_item: 'si_JjEO6dXrmU9kj3',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
    ],
    url:
      '/v1/invoices/upcoming/lines?customer=cus_JjEOpmgLOcKwnO&subscription=sub_JjEOg5XFAs92I5',
  },
  metadata: {},
  next_payment_attempt: 1656055278,
  number: '9CB350B2-0002',
  payment_intent: null,
  period_end: 1656051678,
  period_start: 1624515678,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  status: 'draft',
  status_transitions: {},
  subscription: 'sub_JjEOg5XFAs92I5',
  subtotal: 160000,
  tax: 16000,
  tax_percent: 10,
  total_tax_amounts: [
    {
      amount: 16000,
      tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
    },
  ],
  total: 176000,
};
export const InvoiceFreeData = {
  object: 'invoice',
  account_country: 'AU',
  account_name: 'uGroop Pty. Ltd.',
  billing: 'charge_automatically',
  billing_reason: 'upcoming',
  charge: null,
  collection_method: 'charge_automatically',
  created: 1627182080,
  currency: 'aud',
  customer: 'cus_JjYPMhXzVpyUMb',
  customer_email: 'yuy0311+140520211@gmail.com',
  customer_name: 'Yang Yu',
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [
    {
      id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
      object: 'tax_rate',
      active: true,
      created: 1559609129,
      description: 'GST',
      display_name: 'GST',
      jurisdiction: 'Australia',
      metadata: {},
      percentage: 10,
    },
  ],
  ending_balance: 0,
  lines: {
    object: 'list',
    data: [
      {
        id: 'sli_1ad46bHnywB98SRrc4e2473f',
        object: 'line_item',
        currency: 'aud',
        description: '1 seat × Enterprise (at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1627182080,
          end: 1629860480,
        },
        plan: {
          id: 'plan_FH3wkYtKKHT7IP',
          object: 'plan',
          active: true,
          amount: 0,
          amount_decimal: 0,
          billing_scheme: 'per_unit',
          created: 1560820111,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            EqualPlan: 'Yearly Free',
            description: 'Free',
            firstPurchase: '0',
            type: 'orgseat',
            bundleProduct: 'Free-TourPlan',
          },
          nickname: 'Monthly Free',
          product: 'prod_FBpUnzhhfVzyra',
          usage_type: 'licensed',
        },
        quantity: 1,
        subscription: 'sub_JjYPwJdNmicqKR',
        subscription_item: 'si_JjYP5tdsYl8tmy',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_1fdafeHnywB98SRr1792f0a9',
        object: 'line_item',
        currency: 'aud',
        description: '1 × Enterprise-Tour (at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1627182080,
          end: 1629860480,
        },
        plan: {
          id: 'plan_GHbevWx3SGd8u9',
          object: 'plan',
          active: true,
          amount: 0,
          amount_decimal: 0,
          billing_scheme: 'per_unit',
          created: 1575245211,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Free Tour Seat Plan',
            EqualPlan: 'Free-TourPlan-Yearly',
            type: 'tourseat',
            productInfo:
              'allow you to connect one person as view role per tour',
          },
          nickname: 'Free-TourPlan',
          product: 'prod_G9k7tNPy0S4UNh',
          usage_type: 'licensed',
        },
        quantity: 1,
        subscription: 'sub_JjYPwJdNmicqKR',
        subscription_item: 'si_JjYPpa3ZVmcZwJ',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
    ],
    url:
      '/v1/invoices/upcoming/lines?customer=cus_JjYPMhXzVpyUMb&subscription=sub_JjYPwJdNmicqKR',
  },
  metadata: {},
  next_payment_attempt: 1627185680,
  number: 'FFD706F2-0002',
  payment_intent: null,
  period_end: 1627182080,
  period_start: 1624590080,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  status: 'draft',
  status_transitions: {},
  subscription: 'sub_JjYPwJdNmicqKR',
  tax: 0,
  tax_percent: 10,
  total_tax_amounts: [
    {
      tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
    },
  ],
};
export const UpcomingTourerInvoice = {
  object: 'invoice',
  account_country: 'AU',
  account_name: 'uGroop Pty. Ltd.',
  amount_due: 30800,
  amount_remaining: 30800,
  billing: 'charge_automatically',
  billing_reason: 'upcoming',
  charge: null,
  collection_method: 'charge_automatically',
  created: 1624923685,
  currency: 'aud',
  customer: 'cus_JWV6HWoXIeSXPC',
  customer_email: 'yuy0311+140520211@gmail.com',
  customer_name: 'Yang Yu',
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [
    {
      id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
      object: 'tax_rate',
      active: true,
      created: 1559609129,
      description: 'GST',
      display_name: 'GST',
      jurisdiction: 'Australia',
      metadata: {},
      percentage: 10,
    },
  ],
  ending_balance: 0,
  lines: {
    object: 'list',
    data: [
      {
        id: 'sli_119054HnywB98SRrb7304092',
        object: 'line_item',
        currency: 'aud',
        description: '8 seat × Enterprise (Tier 1 at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624923685,
          end: 1627515685,
        },
        plan: {
          id: 'price_1IvbYZHnywB98SRr7aGleNSS',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622092495,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Tourer',
            firstPurchase: '8',
            EqualPlan: 'Tourer-Yearly',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
          },
          nickname: 'Tourer',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 28000,
              flat_amount_decimal: 28000,
              up_to: 8,
            },
            {
              unit_amount: 4000,
              unit_amount_decimal: 4000,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 8,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNPjB4HbSkm7',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_15d788HnywB98SRr9503c55d',
        object: 'line_item',
        amount: 28000,
        currency: 'aud',
        description: 'Enterprise (Tier 1 at $280.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624923685,
          end: 1627515685,
        },
        plan: {
          id: 'price_1IvbYZHnywB98SRr7aGleNSS',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622092495,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Tourer',
            firstPurchase: '8',
            EqualPlan: 'Tourer-Yearly',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
          },
          nickname: 'Tourer',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 28000,
              flat_amount_decimal: 28000,
              up_to: 8,
            },
            {
              unit_amount: 4000,
              unit_amount_decimal: 4000,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 0,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNPjB4HbSkm7',
        tax_amounts: [
          {
            amount: 2800,
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_147fabHnywB98SRrc0146957',
        object: 'line_item',
        currency: 'aud',
        description: '1 × Enterprise-Tour (at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624923685,
          end: 1627515685,
        },
        plan: {
          id: 'plan_GHbevWx3SGd8u9',
          object: 'plan',
          active: true,
          amount: 0,
          amount_decimal: 0,
          billing_scheme: 'per_unit',
          created: 1575245211,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Free Tour Seat Plan',
            EqualPlan: 'Free-TourPlan-Yearly',
            type: 'tourseat',
            productInfo:
              'allow you to connect one person as view role per tour',
          },
          nickname: 'Free-TourPlan',
          product: 'prod_G9k7tNPy0S4UNh',
          usage_type: 'licensed',
        },
        quantity: 1,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNj4gdps8boz',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
    ],
    url:
      '/v1/invoices/upcoming/lines?customer=cus_JZ6lW1qrYwmn6Y&subscription=sub_JdwNlOjSTIPQtt',
  },
  metadata: {},
  next_payment_attempt: 1624927285,
  number: '08617C45-0003',
  payment_intent: null,
  period_end: 1624923685,
  period_start: 1624923685,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  status: 'draft',
  status_transitions: {},
  subscription: 'sub_JdwNlOjSTIPQtt',
  subscription_proration_date: 1624923685,
  subtotal: 28000,
  tax: 2800,
  tax_percent: 10,
  total_tax_amounts: [
    {
      amount: 2800,
      tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
    },
  ],
  total: 30800,
};
export const UpcomingGranderInvoice = {
  object: 'invoice',
  account_country: 'AU',
  account_name: 'uGroop Pty. Ltd.',
  amount_due: 66000,
  amount_remaining: 66000,
  billing: 'charge_automatically',
  billing_reason: 'upcoming',
  charge: null,
  collection_method: 'charge_automatically',
  created: 1624933286,
  currency: 'aud',
  customer: 'cus_JWV6HWoXIeSXPC',
  customer_email: 'yuy0311+140520211@gmail.com',
  customer_name: 'Yang Yu',
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [
    {
      id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
      object: 'tax_rate',
      active: true,
      created: 1559609129,
      description: 'GST',
      display_name: 'GST',
      jurisdiction: 'Australia',
      metadata: {},
      percentage: 10,
    },
  ],
  ending_balance: 0,
  lines: {
    object: 'list',
    data: [
      {
        id: 'sli_119054HnywB98SRrb7304092',
        object: 'line_item',
        currency: 'aud',
        description: '20 seat × Enterprise (Tier 1 at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624933286,
          end: 1627525286,
        },
        plan: {
          id: 'price_1IvbdMHnywB98SRr4YNkx7l4',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622092792,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            level: 'top',
            description: 'Grand Tourer',
            EqualPlan: 'Grand Tourer-Yearly',
            firstPurchase: '20',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
          },
          nickname: 'Grand Tourer',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 60000,
              flat_amount_decimal: 60000,
              up_to: 20,
            },
            {
              unit_amount: 2500,
              unit_amount_decimal: 2500,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 20,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNPjB4HbSkm7',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_15d788HnywB98SRr9503c55d',
        object: 'line_item',
        amount: 60000,
        currency: 'aud',
        description: 'Enterprise (Tier 1 at $600.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624933286,
          end: 1627525286,
        },
        plan: {
          id: 'price_1IvbdMHnywB98SRr4YNkx7l4',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622092792,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            level: 'top',
            description: 'Grand Tourer',
            EqualPlan: 'Grand Tourer-Yearly',
            firstPurchase: '20',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
          },
          nickname: 'Grand Tourer',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 60000,
              flat_amount_decimal: 60000,
              up_to: 20,
            },
            {
              unit_amount: 2500,
              unit_amount_decimal: 2500,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 0,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNPjB4HbSkm7',
        tax_amounts: [
          {
            amount: 6000,
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_147fabHnywB98SRrc0146957',
        object: 'line_item',
        currency: 'aud',
        description: '1 × Enterprise-Tour (at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624933286,
          end: 1627525286,
        },
        plan: {
          id: 'plan_GHbevWx3SGd8u9',
          object: 'plan',
          active: true,
          amount: 0,
          amount_decimal: 0,
          billing_scheme: 'per_unit',
          created: 1575245211,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Free Tour Seat Plan',
            EqualPlan: 'Free-TourPlan-Yearly',
            type: 'tourseat',
            productInfo:
              'allow you to connect one person as view role per tour',
          },
          nickname: 'Free-TourPlan',
          product: 'prod_G9k7tNPy0S4UNh',
          usage_type: 'licensed',
        },
        quantity: 1,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNj4gdps8boz',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
    ],
    url:
      '/v1/invoices/upcoming/lines?customer=cus_JZ6lW1qrYwmn6Y&subscription=sub_JdwNlOjSTIPQtt',
  },
  metadata: {},
  next_payment_attempt: 1624936886,
  number: '08617C45-0003',
  payment_intent: null,
  period_end: 1624933286,
  period_start: 1624933286,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  status: 'draft',
  status_transitions: {},
  subscription: 'sub_JdwNlOjSTIPQtt',
  subscription_proration_date: 1624933286,
  subtotal: 60000,
  tax: 6000,
  tax_percent: 10,
  total_tax_amounts: [
    {
      amount: 6000,
      tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
    },
  ],
  total: 66000,
};
export const UpcomingStarterInvoice = {
  object: 'invoice',
  account_country: 'AU',
  account_name: 'uGroop Pty. Ltd.',
  amount_due: 17600,
  amount_remaining: 17600,
  billing: 'charge_automatically',
  billing_reason: 'upcoming',
  charge: null,
  collection_method: 'charge_automatically',
  created: 1624933310,
  currency: 'aud',
  customer: 'cus_JWV6HWoXIeSXPC',
  customer_email: 'yuy0311+140520211@gmail.com',
  customer_name: 'Yang Yu',
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [
    {
      id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
      object: 'tax_rate',
      active: true,
      created: 1559609129,
      description: 'GST',
      display_name: 'GST',
      jurisdiction: 'Australia',
      metadata: {},
      percentage: 10,
    },
  ],
  ending_balance: 0,
  lines: {
    object: 'list',
    data: [
      {
        id: 'sli_119054HnywB98SRrb7304092',
        object: 'line_item',
        currency: 'aud',
        description: '4 seat × Enterprise (Tier 1 at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624933310,
          end: 1627525310,
        },
        plan: {
          id: 'price_1Iva8qHnywB98SRrIFZshZOT',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622087056,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Traveller',
            EqualPlan: 'Traveller-Yearly',
            firstPurchase: '4',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
          },
          nickname: 'Traveller',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 16000,
              flat_amount_decimal: 16000,
              up_to: 4,
            },
            {
              unit_amount: 4500,
              unit_amount_decimal: 4500,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 4,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNPjB4HbSkm7',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_15d788HnywB98SRr9503c55d',
        object: 'line_item',
        amount: 16000,
        currency: 'aud',
        description: 'Enterprise (Tier 1 at $160.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624933310,
          end: 1627525310,
        },
        plan: {
          id: 'price_1Iva8qHnywB98SRrIFZshZOT',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622087056,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Traveller',
            EqualPlan: 'Traveller-Yearly',
            firstPurchase: '4',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
          },
          nickname: 'Traveller',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 16000,
              flat_amount_decimal: 16000,
              up_to: 4,
            },
            {
              unit_amount: 4500,
              unit_amount_decimal: 4500,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 0,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNPjB4HbSkm7',
        tax_amounts: [
          {
            amount: 1600,
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_147fabHnywB98SRrc0146957',
        object: 'line_item',
        currency: 'aud',
        description: '1 × Enterprise-Tour (at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624933310,
          end: 1627525310,
        },
        plan: {
          id: 'plan_GHbevWx3SGd8u9',
          object: 'plan',
          active: true,
          amount: 0,
          amount_decimal: 0,
          billing_scheme: 'per_unit',
          created: 1575245211,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Free Tour Seat Plan',
            EqualPlan: 'Free-TourPlan-Yearly',
            type: 'tourseat',
            productInfo:
              'allow you to connect one person as view role per tour',
          },
          nickname: 'Free-TourPlan',
          product: 'prod_G9k7tNPy0S4UNh',
          usage_type: 'licensed',
        },
        quantity: 1,
        subscription: 'sub_JdwNlOjSTIPQtt',
        subscription_item: 'si_JdwNj4gdps8boz',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
    ],
    url:
      '/v1/invoices/upcoming/lines?customer=cus_JZ6lW1qrYwmn6Y&subscription=sub_JdwNlOjSTIPQtt',
  },
  metadata: {},
  next_payment_attempt: 1624936910,
  number: '08617C45-0003',
  payment_intent: null,
  period_end: 1624933310,
  period_start: 1624933310,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  status: 'draft',
  status_transitions: {},
  subscription: 'sub_JdwNlOjSTIPQtt',
  subscription_proration_date: 1624933310,
  subtotal: 16000,
  tax: 1600,
  tax_percent: 10,
  total_tax_amounts: [
    {
      amount: 1600,
      tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
    },
  ],
  total: 17600,
};
export const UpcomingTravellerInvoice = {
  object: 'invoice',
  account_country: 'AU',
  account_name: 'uGroop Pty. Ltd.',
  amount_due: 17600,
  amount_remaining: 17600,
  billing: 'charge_automatically',
  billing_reason: 'upcoming',
  charge: null,
  collection_method: 'charge_automatically',
  created: 1624952862,
  currency: 'aud',
  customer: 'cus_JWV6HWoXIeSXPC',
  customer_email: 'yuy0311@gmail.com',
  customer_name: 'Yang',
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [
    {
      id: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
      object: 'tax_rate',
      active: true,
      created: 1559609129,
      description: 'GST',
      display_name: 'GST',
      jurisdiction: 'Australia',
      metadata: {},
      percentage: 10,
    },
  ],
  ending_balance: 0,
  lines: {
    object: 'list',
    data: [
      {
        id: 'sli_1f1103HnywB98SRr45706c6d',
        object: 'line_item',
        currency: 'aud',
        description: '4 seat × Enterprise (Tier 1 at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624952862,
          end: 1627544862,
        },
        plan: {
          id: 'price_1Iva8qHnywB98SRrIFZshZOT',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622087056,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Traveller',
            EqualPlan: 'Traveller-Yearly',
            firstPurchase: '4',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
          },
          nickname: 'Traveller',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 16000,
              flat_amount_decimal: 16000,
              up_to: 4,
            },
            {
              unit_amount: 4500,
              unit_amount_decimal: 4500,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 4,
        subscription: 'sub_IExiCCb8TAk715',
        subscription_item: 'si_IExiKKGVIAs7OF',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_1229faHnywB98SRre8fec0d6',
        object: 'line_item',
        amount: 16000,
        currency: 'aud',
        description: 'Enterprise (Tier 1 at $160.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624952862,
          end: 1627544862,
        },
        plan: {
          id: 'price_1Iva8qHnywB98SRrIFZshZOT',
          object: 'plan',
          active: true,
          billing_scheme: 'tiered',
          created: 1622087056,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Traveller',
            EqualPlan: 'Traveller-Yearly',
            firstPurchase: '4',
            type: 'orgseat',
            bundleProduct: 'Paid-TourPlan',
          },
          nickname: 'Traveller',
          product: 'prod_FBpUnzhhfVzyra',
          tiers: [
            {
              flat_amount: 16000,
              flat_amount_decimal: 16000,
              up_to: 4,
            },
            {
              unit_amount: 4500,
              unit_amount_decimal: 4500,
            },
          ],
          tiers_mode: 'graduated',
          usage_type: 'licensed',
        },
        quantity: 0,
        subscription: 'sub_IExiCCb8TAk715',
        subscription_item: 'si_IExiKKGVIAs7OF',
        tax_amounts: [
          {
            amount: 1600,
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
      {
        id: 'sli_116c88HnywB98SRr265dea0e',
        object: 'line_item',
        currency: 'aud',
        description: '1 × Enterprise-Tour (at $0.00 / month)',
        discountable: true,
        metadata: {},
        period: {
          start: 1624952862,
          end: 1627544862,
        },
        plan: {
          id: 'plan_GHbevWx3SGd8u9',
          object: 'plan',
          active: true,
          amount: 0,
          amount_decimal: 0,
          billing_scheme: 'per_unit',
          created: 1575245211,
          currency: 'aud',
          interval: 'month',
          interval_count: 1,
          metadata: {
            description: 'Free Tour Seat Plan',
            EqualPlan: 'Free-TourPlan-Yearly',
            type: 'tourseat',
            productInfo:
              'allow you to connect one person as view role per tour',
          },
          nickname: 'Free-TourPlan',
          product: 'prod_G9k7tNPy0S4UNh',
          usage_type: 'licensed',
        },
        quantity: 1,
        subscription: 'sub_IExiCCb8TAk715',
        subscription_item: 'si_IExigJPESnA7im',
        tax_amounts: [
          {
            tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
          },
        ],
        tax_rates: [],
        type: 'subscription',
      },
    ],
    url:
      '/v1/invoices/upcoming/lines?customer=cus_IExiU2HPUopSQQ&subscription=sub_IExiCCb8TAk715',
  },
  metadata: {},
  next_payment_attempt: 1624956462,
  number: 'E51F17FC-0010',
  payment_intent: null,
  period_end: 1624952862,
  period_start: 1624952862,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  status: 'draft',
  status_transitions: {},
  subscription: 'sub_IExiCCb8TAk715',
  subscription_proration_date: 1624952862,
  subtotal: 16000,
  tax: 1600,
  tax_percent: 10,
  total_tax_amounts: [
    {
      amount: 1600,
      tax_rate: 'txr_1EhQmLHnywB98SRrqiRPI5lY',
    },
  ],
  total: 17600,
};
